const List<Map<String, String>> indhiyaMaanilangal = [
  {"en": "Andaman and Nicobar Islands", "ta": "அந்தமான் நிக்கோபார் தீவுகள்"},
  {"en": "Andhra Pradesh", "ta": "ஆந்திரப் பிரதேசம்"},
  {"en": "Arunachal Pradesh", "ta": "அருணாசலப் பிரதேசம்"},
  {"en": "Assam", "ta": "அசாம்"},
  {"en": "Bihar", "ta": "பீகார்"},
  {"en": "Chandigarh", "ta": "சண்டிகர்"},
  {"en": "Chhattisgarh", "ta": "சத்தீசுகர்"},
  {"en": "Dadra and Nagar Haveli and Daman and Diu", "ta": "தாத்ரா மற்றும் நகர் அவேலி மற்றும் தாமன் மற்றும் தியூ"},
  {"en": "Delhi", "ta": "தில்லி"},
  {"en": "Goa", "ta": "கோவா"},
  {"en": "Gujarat", "ta": "குசராத்து"},
  {"en": "Haryana", "ta": "அரியாணா"},
  {"en": "Himachal Pradesh", "ta": "இமாசலப் பிரதேசம்"},
  {"en": "Jammu and Kashmir", "ta": "சம்மு காசுமீர்"},
  {"en": "Jharkhand", "ta": "சார்க்கண்டு"},
  {"en": "Karnataka", "ta": "கருநாடகம்"},
  {"en": "Kerala", "ta": "கேரளம்"},
  {"en": "Ladakh", "ta": "இலடாக்"},
  {"en": "Lakshadweep", "ta": "இலட்சத்தீவுகள்"},
  {"en": "Madhya Pradesh", "ta": "மத்தியப் பிரதேசம்"},
  {"en": "Maharashtra", "ta": "மகாராட்டிரம்"},
  {"en": "Manipur", "ta": "மணிப்பூர்"},
  {"en": "Meghalaya", "ta": "மேகாலயா"},
  {"en": "Mizoram", "ta": "மிசோரம்"},
  {"en": "Nagaland", "ta": "நாகாலாந்து"},
  {"en": "Odisha", "ta": "ஒடிசா"},
  {"en": "Puducherry", "ta": "புதுச்சேரி"},
  {"en": "Punjab", "ta": "பஞ்சாபு"},
  {"en": "Rajasthan", "ta": "இராசத்தான்"},
  {"en": "Sikkim", "ta": "சிக்கிம்"},
  {"en": "Tamil Nadu", "ta": "தமிழ்நாடு"},
  {"en": "Telangana", "ta": "தெலுங்கானா"},
  {"en": "Tripura", "ta": "திரிபுரா"},
  {"en": "Uttar Pradesh", "ta": "உத்தரப் பிரதேசம்"},
  {"en": "Uttarakhand", "ta": "உத்தராகண்டம்"},
  {"en": "West Bengal", "ta": "மேற்கு வங்காளம்"},
  {"en": "Custom", "ta": "தனிப்பயன்"}
];
