const List<Map<String, String>> ulagaNaadugal = [
  {"en": "India", "ta": "இந்தியா"},
  {"en": "United States", "ta": "அமெரிக்க ஒன்றிணைந்த நாடுகள்"},
  {"en": "United Kingdom", "ta": "ஒன்றிணைந்த பேரரசு"},
  {"en": "Canada", "ta": "கனடா"},
  {"en": "Australia", "ta": "ஆஸ்திரேலியா"},
  {"en": "New Zealand", "ta": "நியூசிலாந்து"},
  {"en": "Japan", "ta": "நிஹொன்"},
  {"en": "South Korea", "ta": "ஹங்குக்கு"},
  {"en": "China", "ta": "சீனா"},
  {"en": "France", "ta": "ஃபிரான்சு"},
  {"en": "Germany", "ta": "டொயிச்சுலாந்து"},
  {"en": "Italy", "ta": "இத்தாலியா"},
  {"en": "Spain", "ta": "எசுப்பானியா"},
  {"en": "Netherlands", "ta": "நெதர்லாந்து"},
  {"en": "Singapore", "ta": "சிங்கப்பூர்"},
  {"en": "Malaysia", "ta": "மலேசியா"},
  {"en": "Indonesia", "ta": "இந்தோனேசியா"},
  {"en": "Thailand", "ta": "தாய்லாந்து"},
  {"en": "United Arab Emirates", "ta": "ஒன்றிணைந்த அரபு அமீரகம்"},
  {"en": "Saudi Arabia", "ta": "சவுதி அரேபியா"},
  {"en": "South Africa", "ta": "தென் ஆப்பிரிக்கா"},
  {"en": "Sri Lanka", "ta": "இலங்கை"},
  {"en": "Bangladesh", "ta": "வங்காளதேசம்"},
  {"en": "Nepal", "ta": "நேபாளம்"},
  {"en": "Pakistan", "ta": "பாகிஸ்தான்"},
  {"en": "Philippines", "ta": "பிலிப்பினாசு"},
  {"en": "Custom", "ta": "தனிப்பயன்"}
];
