/// Mock Seed Data — Extracted from Firebase RTDB Export
///
/// Key naming rules:
/// - All keys use pure Tamil transliteration (no English, no Sanskrit)
/// - Bilingual fields use `_Tamil` / `_English` suffix (language tags)
/// - Universal acronyms (gstin, ifsc, upi) stay as-is
/// - Non-bilingual fields (numbers, emails, codes) have no suffix

library;

/// A visible 32×32 purple (#6a1b9a) placeholder PNG, base64-encoded.
/// Used for mock logos/signatures when no real image is available.
const _mockOavuru =
    'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAIAAAD8GO2jAAAAK0lEQVR4nGPIkp5FU8QwasGoBaMWjFowasGoBaMWjFowasGoBaMWSA8RCwCj8Hw9ZAkoRwAAAABJRU5ErkJggg==';

// ─────────────────────────────────────────────────────────────────────────────
// SILK MODE PROFILE — SJPS (ஶ்ரீ ஜெய்பிரியா சில்க்ஸ்)
// From Firebase: profile + thannilai/biz_1780841787530
// ─────────────────────────────────────────────────────────────────────────────

const List<Map<String, dynamic>> mockSilkProfiles = [
  {
    'mudhanMozhi': 'ta',
    'thunaiMozhi': 'en',
    'iruMozhi': true,
    'niruvanathinPeyar_ta': 'ஶ்ரீ ஜெய்பிரியா சில்க்ஸ்',
    'niruvanathinPeyar_en': 'Sri Jaipriya Silks',
    'kurumPeyar': 'SJPS',
    'tholaipesi_1': '8144604797',
    'tholaipesi_2': '9360779191',
    'minnanjal': 'srijaipriyasilks@gmail.com',
    'gstin': '33ASSPV0378E1ZD',
    'mugavari_ta': '4/606, முதல் தெரு, சிவசக்தி நகர்',
    'mugavari_en': '4/606, First Street, Sivasakthi Nagar',
    'oor_ta': 'ஆரணி',
    'oor_en': 'Arani',
    'maavattam_ta': 'திருவண்ணாமலை',
    'maavattam_en': 'Thiruvannamalai',
    'maanilam_ta': 'தமிழ்நாடு',
    'maanilam_en': 'Tamil Nadu',
    'naadu_ta': 'இந்தியா',
    'naadu_en': 'India',
    'anjalKuriyeedu': '632317',
    'vangiPeyar_ta': 'தமிழ்நாடு மெர்கன்டைல் வங்கி',
    'vangiPeyar_en': 'Tamilnad Mercantile Bank',
    'kilai_ta': 'ஆரணி',
    'kilai_en': 'Arani',
    'vangiKanakku': '309150050800239',
    'ifsc': 'TMBL0000309',
    'oavuru': _mockOavuru,
    'agalaOavuru': _mockOavuru,
    'thalaippuVadivu': 'wide',
    'kaiyoppam': _mockOavuru,
    'oppamPeyar': 'பா. வனிதாஶ்ரீ',
    'adaimozhi_ta': 'கைத்தறி பட்டு சேலைகள் & ராசில்க்',
    'adaimozhi_en': 'Handloom Silk Sarees & Rawsilk',
    'upiId': 'srijaipriya@ybl',
    'thoatraNiram': '#6a1b9a',
  },
  // ── EPS (எல்வன் பட்டுக்கடை) — DEV EXTRA PROFILE ──
  {
    'mudhanMozhi': 'ta',
    'thunaiMozhi': 'en',
    'iruMozhi': true,
    'niruvanathinPeyar_ta': 'எல்வன் பட்டுக்கடை',
    'niruvanathinPeyar_en': 'Elvan Pattu Kadai',
    'kurumPeyar': 'EPS',
    'tholaipesi_1': '9876543210',
    'tholaipesi_2': '',
    'minnanjal': 'elvanpattu@test.com',
    'gstin': '33AABCE1234F1ZH',
    'mugavari_ta': '12, நெசவாளர் தெரு',
    'mugavari_en': '12, Weaver Street',
    'oor_ta': 'காஞ்சிபுரம்',
    'oor_en': 'Kanchipuram',
    'maavattam_ta': 'காஞ்சிபுரம்',
    'maavattam_en': 'Kanchipuram',
    'maanilam_ta': 'தமிழ்நாடு',
    'maanilam_en': 'Tamil Nadu',
    'naadu_ta': 'இந்தியா',
    'naadu_en': 'India',
    'anjalKuriyeedu': '631501',
    'vangiPeyar_ta': 'இந்தியன் வங்கி',
    'vangiPeyar_en': 'Indian Bank',
    'kilai_ta': 'காஞ்சிபுரம்',
    'kilai_en': 'Kanchipuram',
    'vangiKanakku': '456789012345',
    'ifsc': 'IDIB000K123',
    'oavuru': _mockOavuru,
    'agalaOavuru': _mockOavuru,
    'thalaippuVadivu': 'small',
    'kaiyoppam': _mockOavuru,
    'oppamPeyar': 'எ. பார்த்தசாரதி',
    'adaimozhi_ta': 'கைத்தறி மற்றும் விசைத்தறி பட்டு',
    'adaimozhi_en': 'Handloom & Powerloom Silk',
    'upiId': 'elvanpattu@upi',
    'thoatraNiram': '#1565c0',
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// COOLIE MODE PROFILES — VRM & PVS
// From Firebase: coolie_thannilai
// ─────────────────────────────────────────────────────────────────────────────

const List<Map<String, dynamic>> mockCoolieProfiles = [
  // ── VRM (வி.ஆர்.எம். பட்டு முறுக்கு ஆலை) ──
  {
    'mudhanMozhi': 'ta',
    'thunaiMozhi': 'en',
    'iruMozhi': true,
    'niruvanathinPeyar_ta': 'வி.ஆர்.எம். பட்டு முறுக்கு ஆலை',
    'niruvanathinPeyar_en': 'V.R.M. Silk Twisting Factory',
    'kurumPeyar': 'VRM',
    'tholaipesi_1': '8144604797',
    'tholaipesi_2': '9360779191',
    'minnanjal': 'vrmshreesarathy@gmail.com',
    'gstin': '',
    'mugavari_ta': '4/606, முதல் தெரு, சிவசக்தி நகர்',
    'mugavari_en': '4/606, First Street, Sivasakthi Nagar',
    'oor_ta': 'ஆரணி',
    'oor_en': 'Arani',
    'maavattam_ta': 'திருவண்ணாமலை',
    'maavattam_en': 'Thiruvannamalai',
    'maanilam_ta': 'தமிழ்நாடு',
    'maanilam_en': 'Tamil Nadu',
    'naadu_ta': 'இந்தியா',
    'naadu_en': 'India',
    'anjalKuriyeedu': '632301',
    'vangiPeyar_ta': 'தமிழ்நாடு மெர்கன்டைல் வங்கி',
    'vangiPeyar_en': 'Tamilnad Mercantile Bank',
    'kilai_ta': 'ஆரணி',
    'kilai_en': 'Arani',
    'vangiKanakku': '309150050800162',
    'ifsc': 'TMBL0000309',
    'oavuru': _mockOavuru,
    'agalaOavuru': _mockOavuru,
    'kaiyoppam': _mockOavuru,
    'oppamPeyar': 'இரா. பார்த்தசாரதி',
    'adaimozhi_ta': '',
    'adaimozhi_en': '',
    'upiId': '',
    'thoatraNiram': '#6a1b9a',
  },

  // ── PVS (பி.வி.எஸ். சில்க் டுவிஸ்டிங்) ──
  {
    'mudhanMozhi': 'ta',
    'thunaiMozhi': 'en',
    'iruMozhi': true,
    'niruvanathinPeyar_ta': 'பி.வி.எஸ். சில்க் டுவிஸ்டிங்',
    'niruvanathinPeyar_en': 'P.V.S. Silk Twisting',
    'kurumPeyar': 'PVS',
    'tholaipesi_1': '8144604797',
    'tholaipesi_2': '9360779191',
    'minnanjal': 'vrmshreesarathy@gmail.com',
    'gstin': '',
    'mugavari_ta': '4/606, முதல் தெரு, சிவசக்தி நகர்',
    'mugavari_en': '4/606, First Street, Sivasakthi Nagar',
    'oor_ta': 'ஆரணி',
    'oor_en': 'Arani',
    'maavattam_ta': 'திருவண்ணாமலை',
    'maavattam_en': 'Thiruvannamalai',
    'maanilam_ta': 'தமிழ்நாடு',
    'maanilam_en': 'Tamil Nadu',
    'naadu_ta': 'இந்தியா',
    'naadu_en': 'India',
    'anjalKuriyeedu': '632301',
    'vangiPeyar_ta': 'தமிழ்நாடு மெர்கன்டைல் வங்கி',
    'vangiPeyar_en': 'Tamilnad Mercantile Bank',
    'kilai_ta': 'ஆரணி',
    'kilai_en': 'Arani',
    'vangiKanakku': '309150050800162',
    'ifsc': 'TMBL0000309',
    'oavuru': _mockOavuru,
    'agalaOavuru': _mockOavuru,
    'kaiyoppam': _mockOavuru,
    'oppamPeyar': 'பா. வனிதாஶ்ரீ',
    'adaimozhi_ta': '',
    'adaimozhi_en': '',
    'upiId': '',
    'thoatraNiram': '#6a1b9a',
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// COOLIE MODE PRODUCTS (Porul) — from Firebase RTDB export (de-duplicated)
// ─────────────────────────────────────────────────────────────────────────────

const List<Map<String, dynamic>> mockCooliePorulgal = [
  {
    'peyar_ta': 'இரண்டு இழை சப்புரி செய்ய கூலி',
    'peyar_en': 'Irandu Izhai Sappuri Seiyya Coolie',
  },
  {
    'peyar_ta': 'ஜரி தடை செய்ய கூலி',
    'peyar_en': 'Jari Dhadai Cheiya Coolie',
  },
  {
    'peyar_ta': 'மூன்று இழை சப்புரி செய்ய கூலி',
    'peyar_en': 'Moondru Izhai Sappuri Cheiya Coolie',
  },
  {
    'peyar_ta': 'ஒண்டி தடை செய்ய கூலி',
    'peyar_en': 'Ondi Dhadai Cheiya Coolie',
  },
  {
    'peyar_ta': 'கச்சா பட்டு',
    'peyar_en': 'Raw Silk',
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// SILK MODE PRODUCTS (Porul) — from Firebase RTDB export (de-duplicated)
// ─────────────────────────────────────────────────────────────────────────────

const List<Map<String, dynamic>> mockSilkPorulgal = [
  {
    'peyar_ta': 'கச்சா பட்டு',
    'peyar_en': 'Raw Silk',
    'hsnCode': '50072000',
    'vilai': 5806.0,
    'variVeetham': 0.0,
    'alagu': 'Kg',
    'alavuVagai': 'weight',
  },
  {
    'peyar_ta': 'முறுக்கு பட்டு',
    'peyar_en': 'Twisted Silk',
    'hsnCode': '50072019',
    'vilai': 18900.0,
    'variVeetham': 0.0,
    'alagu': 'Kg',
    'alavuVagai': 'weight',
  },
  {
    'peyar_ta': 'ஃபேன்ஸி சேலை',
    'peyar_en': 'Fancy Saree',
    'hsnCode': '50072010',
    'vilai': 7900.0,
    'variVeetham': 5.0,
    'alagu': 'Nos',
    'alavuVagai': 'quantity',
  },
  {
    'peyar_ta': 'ஃபேன்ஸி முத்து முந்தி கட்டம் சேலை',
    'peyar_en': 'Fancy Muthu Mundhi Kattam Saree',
    'hsnCode': '50072010',
    'vilai': 8200.0,
    'variVeetham': 5.0,
    'alagu': 'Nos',
    'alavuVagai': 'quantity',
  },
  {
    'peyar_ta': 'ஃபேன்ஸி கட்டம் புட்டா',
    'peyar_en': 'Fancy Checked Butta',
    'hsnCode': '50072010',
    'vilai': 8500.0,
    'variVeetham': 5.0,
    'alagu': 'Nos',
    'alavuVagai': 'quantity',
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// COOLIE MODE CUSTOMERS (Vaangunar) — from Firebase RTDB export
// ─────────────────────────────────────────────────────────────────────────────

const List<Map<String, dynamic>> mockCoolieVaangunargal = [
  {
    'peyar_ta': 'சுந்தரி சில்க்ஸ் இந்தியா',
    'peyar_en': 'Sundari Silks India',
    'oor_ta': 'முள்ளிப்பட்டு, ஆரணி',
    'oor_en': 'Mullippattu, Arani',
  },
  {
    'peyar_ta': 'சுந்தரி சில்க்ஸ் இந்தியா',
    'peyar_en': 'Sundari Silks India',
    'oor_ta': 'திருச்சேறை, கும்பகோணம்',
    'oor_en': 'Thirucherai, Kumbakonam',
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// SILK MODE CUSTOMERS (Vaangunar) — from Firebase RTDB export
// ─────────────────────────────────────────────────────────────────────────────

const List<Map<String, dynamic>> mockSilkVaangunargal = [
  {
    'peyar_ta': 'ஸ்ரீ சிவராம் சில்க் சாரீஸ்',
    'peyar_en': 'Sri Sivaram Silk Sarees',
    'mugavari_ta': 'எண் 6, ஒளவையார் தெரு',
    'mugavari_en': 'No 6, Avvaiyaar Street',
    'oor_ta': 'ஆரணி',
    'oor_en': 'Arani',
    'maavattam_ta': 'திருவண்ணாமலை',
    'maavattam_en': 'Thiruvannamalai',
    'maanilam_ta': 'தமிழ்நாடு',
    'maanilam_en': 'Tamil Nadu',
    'naadu_ta': 'இந்தியா',
    'naadu_en': 'India',
    'anjalKuriyeedu': '632301',
    'gstin': '33AYGPS0561E1ZN',
  },
];

/// Mock Coolie invoices extracted from Firebase RTDB export.
/// These seed actual production data for testing the dashboard.
const List<Map<String, dynamic>> mockCooliePattiyalgal = [
  {
    'bill_no': 'VRM-103',
    'customer_name': 'சுந்தரி சில்க்ஸ் இந்தியா',
    'customer_name_en': 'Sundari Silks India',
    'customer_oor': 'திருச்சேறை, கும்பகோணம்',
    'date': '21/02/2026',
    'grand_total': 16043,
    'mothaEdai': 26.3,
    'setharamGrams': 950.0,
    'thabaalThogai': 0.0,
    'ahimsaPattuThogai': 0.0,
    'items': '[{"porulPeyar": "ஜரி தடை செய்ய கூலி", "edai": 26.3, "vilai": 610.0}]',
  },
  {
    'bill_no': 'PVS-20',
    'customer_name': 'சுந்தரி சில்க்ஸ் இந்தியா',
    'customer_name_en': 'Sundari Silks India',
    'customer_oor': 'திருச்சேறை, கும்பகோணம்',
    'date': '30/03/2026',
    'grand_total': 12489,
    'mothaEdai': 27.65,
    'setharamGrams': 1300.0,
    'thabaalThogai': 600.0,
    'ahimsaPattuThogai': 0.0,
    'items': '[{"porulPeyar": "மூன்று இழை சப்புரி செய்ய கூலி", "edai": 27.65, "vilai": 430.0}]',
  },
  {
    'bill_no': 'VRM-105',
    'customer_name': 'சுந்தரி சில்க்ஸ் இந்தியா',
    'customer_name_en': 'Sundari Silks India',
    'customer_oor': 'முள்ளிப்பட்டு, ஆரணி',
    'date': '04/03/2026',
    'grand_total': 18860,
    'mothaEdai': 37.83,
    'setharamGrams': 1370.0,
    'thabaalThogai': 0.0,
    'ahimsaPattuThogai': 0.0,
    'items': '[{"porulPeyar": "ஜரி தடை செய்ய கூலி", "edai": 19.5, "vilai": 610.0}, {"porulPeyar": "மூன்று இழை சப்புரி செய்ய கூலி", "edai": 18.33, "vilai": 380.0}]',
  },
  {
    'bill_no': 'PVS-16',
    'customer_name': 'சுந்தரி சில்க்ஸ் இந்தியா',
    'customer_name_en': 'Sundari Silks India',
    'customer_oor': 'திருச்சேறை, கும்பகோணம்',
    'date': '12/02/2026',
    'grand_total': 17714,
    'mothaEdai': 32.52,
    'setharamGrams': 1530.0,
    'thabaalThogai': 700.0,
    'ahimsaPattuThogai': 0.0,
    'items': '[{"porulPeyar": "ஒண்டி தடை செய்ய கூலி", "edai": 13.18, "vilai": 660.0}, {"porulPeyar": "மூன்று இழை சப்புரி செய்ய கூலி", "edai": 19.34, "vilai": 430.0}]',
  },
  {
    'bill_no': 'VRM-104',
    'customer_name': 'சுந்தரி சில்க்ஸ் இந்தியா',
    'customer_name_en': 'Sundari Silks India',
    'customer_oor': 'முள்ளிப்பட்டு, ஆரணி',
    'date': '25/02/2026',
    'grand_total': 9773,
    'mothaEdai': 25.72,
    'setharamGrams': 930.0,
    'thabaalThogai': 0.0,
    'ahimsaPattuThogai': 0.0,
    'items': '[{"porulPeyar": "இரண்டு இழை சப்புரி செய்ய கூலி", "edai": 25.72, "vilai": 380.0}]',
  },
  {
    'bill_no': 'VRM-107',
    'customer_name': 'சுந்தரி சில்க்ஸ் இந்தியா',
    'customer_name_en': 'Sundari Silks India',
    'customer_oor': 'முள்ளிப்பட்டு, ஆரணி',
    'date': '23/03/2026',
    'grand_total': 11552,
    'mothaEdai': 30.4,
    'setharamGrams': 1100.0,
    'thabaalThogai': 0.0,
    'ahimsaPattuThogai': 0.0,
    'items': '[{"porulPeyar": "இரண்டு இழை சப்புரி செய்ய கூலி", "edai": 30.4, "vilai": 380.0}]',
  },
  {
    'bill_no': 'PVS-18',
    'customer_name': 'சுந்தரி சில்க்ஸ் இந்தியா',
    'customer_name_en': 'Sundari Silks India',
    'customer_oor': 'திருச்சேறை, கும்பகோணம்',
    'date': '09/03/2026',
    'grand_total': 14607,
    'mothaEdai': 30.13,
    'setharamGrams': 1420.0,
    'thabaalThogai': 640.0,
    'ahimsaPattuThogai': 0.0,
    'items': '[{"porulPeyar": "ஒண்டி தடை செய்ய கூலி", "edai": 4.4, "vilai": 660.0}, {"porulPeyar": "மூன்று இழை சப்புரி செய்ய கூலி", "edai": 25.73, "vilai": 430.0}]',
  },
  {
    'bill_no': 'VRM-111',
    'customer_name': 'சுந்தரி சில்க்ஸ் இந்தியா',
    'customer_name_en': 'Sundari Silks India',
    'customer_oor': 'முள்ளிப்பட்டு, ஆரணி',
    'date': '24/04/2026',
    'grand_total': 11460,
    'mothaEdai': 30.16,
    'setharamGrams': 1090.0,
    'thabaalThogai': 0.0,
    'ahimsaPattuThogai': 0.0,
    'items': '[{"porulPeyar": "இரண்டு இழை சப்புரி செய்ய கூலி", "edai": 30.16, "vilai": 380.0}]',
  },
  {
    'bill_no': 'VRM-106',
    'customer_name': 'சுந்தரி சில்க்ஸ் இந்தியா',
    'customer_name_en': 'Sundari Silks India',
    'customer_oor': 'முள்ளிப்பட்டு, ஆரணி',
    'date': '23/03/2026',
    'grand_total': 14688,
    'mothaEdai': 24.08,
    'setharamGrams': 870.0,
    'thabaalThogai': 0.0,
    'ahimsaPattuThogai': 0.0,
    'items': '[{"porulPeyar": "ஜரி தடை செய்ய கூலி", "edai": 24.08, "vilai": 610.0}]',
  },
  {
    'bill_no': 'VRM-112',
    'customer_name': 'சுந்தரி சில்க்ஸ் இந்தியா',
    'customer_name_en': 'Sundari Silks India',
    'customer_oor': 'திருச்சேறை, கும்பகோணம்',
    'date': '13/05/2026',
    'grand_total': 17543,
    'mothaEdai': 28.76,
    'setharamGrams': 1040.0,
    'thabaalThogai': 0.0,
    'ahimsaPattuThogai': 0.0,
    'items': '[{"porulPeyar": "ஜரி தடை செய்ய கூலி", "edai": 28.76, "vilai": 610.0}]',
  },
  {
    'bill_no': 'PVS-23',
    'customer_name': 'சுந்தரி சில்க்ஸ் இந்தியா',
    'customer_name_en': 'Sundari Silks India',
    'customer_oor': 'திருச்சேறை, கும்பகோணம்',
    'date': '22/05/2026',
    'grand_total': 15892,
    'mothaEdai': 23.14,
    'setharamGrams': 960.0,
    'thabaalThogai': 620.0,
    'ahimsaPattuThogai': 0.0,
    'items': '[{"porulPeyar": "ஒண்டி தடை செய்ய கூலி", "edai": 23.14, "vilai": 660.0}]',
  },
  {
    'bill_no': 'VRM-108',
    'customer_name': 'சுந்தரி சில்க்ஸ் இந்தியா',
    'customer_name_en': 'Sundari Silks India',
    'customer_oor': 'திருச்சேறை, கும்பகோணம்',
    'date': '28/03/2026',
    'grand_total': 18367,
    'mothaEdai': 30.11,
    'setharamGrams': 1090.0,
    'thabaalThogai': 0.0,
    'ahimsaPattuThogai': 0.0,
    'items': '[{"porulPeyar": "ஜரி தடை செய்ய கூலி", "edai": 30.11, "vilai": 610.0}]',
  },
  {
    'bill_no': 'PVS-17',
    'customer_name': 'சுந்தரி சில்க்ஸ் இந்தியா',
    'customer_name_en': 'Sundari Silks India',
    'customer_oor': 'திருச்சேறை, கும்பகோணம்',
    'date': '17/02/2026',
    'grand_total': 13359,
    'mothaEdai': 25.5,
    'setharamGrams': 1200.0,
    'thabaalThogai': 600.0,
    'ahimsaPattuThogai': 0.0,
    'items': '[{"porulPeyar": "ஒண்டி தடை செய்ய கூலி", "edai": 7.8, "vilai": 660.0}, {"porulPeyar": "மூன்று இழை சப்புரி செய்ய கூலி", "edai": 17.7, "vilai": 430.0}]',
  },
  {
    'bill_no': 'PVS-21',
    'customer_name': 'சுந்தரி சில்க்ஸ் இந்தியா',
    'customer_name_en': 'Sundari Silks India',
    'customer_oor': 'திருச்சேறை, கும்பகோணம்',
    'date': '25/04/2026',
    'grand_total': 15960,
    'mothaEdai': 33.38,
    'setharamGrams': 1570.0,
    'thabaalThogai': 0.0,
    'ahimsaPattuThogai': 0.0,
    'items': '[{"porulPeyar": "ஜரி தடை செய்ய கூலி", "edai": 8.93, "vilai": 610.0}, {"porulPeyar": "மூன்று இழை சப்புரி செய்ய கூலி", "edai": 24.45, "vilai": 430.0}]',
  },
  {
    'bill_no': 'PVS-22',
    'customer_name': 'சுந்தரி சில்க்ஸ் இந்தியா',
    'customer_name_en': 'Sundari Silks India',
    'customer_oor': 'திருச்சேறை, கும்பகோணம்',
    'date': '18/05/2026',
    'grand_total': 17501,
    'mothaEdai': 33.5,
    'setharamGrams': 1600.0,
    'thabaalThogai': 900.0,
    'ahimsaPattuThogai': 0.0,
    'items': '[{"porulPeyar": "ஒண்டி தடை செய்ய கூலி", "edai": 9.55, "vilai": 660.0}, {"porulPeyar": "மூன்று இழை சப்புரி செய்ய கூலி", "edai": 23.95, "vilai": 430.0}]',
  },
  {
    'bill_no': 'VRM-101',
    'customer_name': 'சுந்தரி சில்க்ஸ் இந்தியா',
    'customer_name_en': 'Sundari Silks India',
    'customer_oor': 'திருச்சேறை, கும்பகோணம்',
    'date': '06/02/2026',
    'grand_total': 17751,
    'mothaEdai': 29.1,
    'setharamGrams': 1050.0,
    'thabaalThogai': 0.0,
    'ahimsaPattuThogai': 0.0,
    'items': '[{"porulPeyar": "ஜரி தடை செய்ய கூலி", "edai": 29.1, "vilai": 610.0}]',
  },
  {
    'bill_no': 'VRM-115',
    'customer_name': 'சுந்தரி சில்க்ஸ் இந்தியா',
    'customer_name_en': 'Sundari Silks India',
    'customer_oor': 'திருச்சேறை, கும்பகோணம்',
    'date': '27/05/2026',
    'grand_total': 12799,
    'mothaEdai': 33.68,
    'setharamGrams': 1220.0,
    'thabaalThogai': 0.0,
    'ahimsaPattuThogai': 1.0,
    'items': '[{"porulPeyar": "இரண்டு இழை சப்புரி செய்ய கூலி", "edai": 33.68, "vilai": 380.0}]',
  },
  {
    'bill_no': 'VRM-113',
    'customer_name': 'சுந்தரி சில்க்ஸ் இந்தியா',
    'customer_name_en': 'Sundari Silks India',
    'customer_oor': 'முள்ளிப்பட்டு, ஆரணி',
    'date': '14/05/2026',
    'grand_total': 12228,
    'mothaEdai': 32.18,
    'setharamGrams': 1170.0,
    'thabaalThogai': 0.0,
    'ahimsaPattuThogai': 0.0,
    'items': '[{"porulPeyar": "இரண்டு இழை சப்புரி செய்ய கூலி", "edai": 32.18, "vilai": 380.0}]',
  },
  {
    'bill_no': 'PVS-24',
    'customer_name': 'சுந்தரி சில்க்ஸ் இந்தியா',
    'customer_name_en': 'Sundari Silks India',
    'customer_oor': 'முள்ளிப்பட்டு, ஆரணி',
    'date': '12/06/2026',
    'grand_total': 16141,
    'mothaEdai': 35.33,
    'setharamGrams': 1670.0,
    'thabaalThogai': 950.0,
    'ahimsaPattuThogai': 0.0,
    'items': '[{"porulPeyar": "இரண்டு இழை சப்புரி செய்ய கூலி", "edai": 35.33, "vilai": 430.0}]',
  },
  {
    'bill_no': 'VRM-109',
    'customer_name': 'சுந்தரி சில்க்ஸ் இந்தியா',
    'customer_name_en': 'Sundari Silks India',
    'customer_oor': 'முள்ளிப்பட்டு, ஆரணி',
    'date': '04/04/2026',
    'grand_total': 9481,
    'mothaEdai': 24.95,
    'setharamGrams': 900.0,
    'thabaalThogai': 0.0,
    'ahimsaPattuThogai': 0.0,
    'items': '[{"porulPeyar": "இரண்டு இழை சப்புரி செய்ய கூலி", "edai": 24.95, "vilai": 380.0}]',
  },
  {
    'bill_no': 'PVS-19',
    'customer_name': 'சுந்தரி சில்க்ஸ் இந்தியா',
    'customer_name_en': 'Sundari Silks India',
    'customer_oor': 'முள்ளிப்பட்டு, ஆரணி',
    'date': '20/03/2026',
    'grand_total': 15846,
    'mothaEdai': 29.18,
    'setharamGrams': 1220.0,
    'thabaalThogai': 620.0,
    'ahimsaPattuThogai': 0.0,
    'items': '[{"porulPeyar": "ஒண்டி தடை செய்ய கூலி", "edai": 11.65, "vilai": 660.0}, {"porulPeyar": "மூன்று இழை சப்புரி செய்ய கூலி", "edai": 17.53, "vilai": 430.0}]',
  },
];

/// Mock Silk (GST) invoices for SJPS — exact data from Firebase RTDB export.
const List<Map<String, dynamic>> mockSilkPattiyalgal = [
  {
    'invoiceNumber': 'SJPS-29',
    'invoiceDate': '2026-06-11',
    'invoiceType': 'tax-invoice',
    'customer_name': 'ஸ்ரீ சிவராம் சில்க் சாரீஸ்',
    'customer_name_en': 'Sri Sivaram Silk Sarees',
    'grandTotal': 139924.6,
    'totalDiscount': 0.0,
    'totalTax': 0.0,
    'items': '[{"porulPeyar": "கச்சா பட்டு", "hsnKuriyeedu": "50072000", "alavu": 24.1, "alagu": "Kg", "vilai": 5806.0, "variVizhukkaadu": 0.0, "thallupadi": 0.0, "thallupadiVagai": \"₹\"}]',
  },
  {
    'invoiceNumber': 'SJPS-31',
    'invoiceDate': '2026-06-11',
    'invoiceType': 'tax-invoice',
    'customer_name': 'ஸ்ரீ சிவராம் சில்க் சாரீஸ்',
    'customer_name_en': 'Sri Sivaram Silk Sarees',
    'grandTotal': 52365011.2,
    'totalDiscount': 0.0,
    'totalTax': 0.0,
    'items': '[{"porulPeyar": "கச்சா பட்டு", "hsnKuriyeedu": "50072000", "alavu": 1400.2, "alagu": "Kg", "vilai": 5806.0, "variVizhukkaadu": 0.0, "thallupadi": 0.0, "thallupadiVagai": \"₹\"}, {"porulPeyar": "முறுக்கு பட்டு", "hsnKuriyeedu": "50072019", "alavu": 2340.5, "alagu": "Kg", "vilai": 18900.0, "variVizhukkaadu": 0.0, "thallupadi": 0.0, "thallupadiVagai": \"₹\"}]',
  },
  {
    'invoiceNumber': 'SJPS-32',
    'invoiceDate': '2026-06-17',
    'invoiceType': 'tax-invoice',
    'customer_name': 'ஸ்ரீ சிவராம் சில்க் சாரீஸ்',
    'customer_name_en': 'Sri Sivaram Silk Sarees',
    'grandTotal': 75811.05,
    'totalDiscount': 99.0,
    'totalTax': 3610.05,
    'items': '[{"porulPeyar": "ஃபேன்ஸி சேலை", "hsnKuriyeedu": "50072010", "alavu": 6.0, "alagu": "Nos", "vilai": 7900.0, "variVizhukkaadu": 5.0, "thallupadi": 0.0, "thallupadiVagai": \"₹\"}, {"porulPeyar": "ஃபேன்ஸி முத்து முந்தி கட்டம் சேலை", "hsnKuriyeedu": "50072010", "alavu": 1.0, "alagu": "Nos", "vilai": 8200.0, "variVizhukkaadu": 5.0, "thallupadi": 0.0, "thallupadiVagai": \"₹\"}, {"porulPeyar": "ஃபேன்ஸி முத்து முந்தி கட்டம் சேலை", "hsnKuriyeedu": "50072010", "alavu": 1.0, "alagu": "Nos", "vilai": 8200.0, "variVizhukkaadu": 5.0, "thallupadi": 0.0, "thallupadiVagai": \"₹\"}, {"porulPeyar": "ஃபேன்ஸி கட்டம் புட்டா", "hsnKuriyeedu": "50072010", "alavu": 1.0, "alagu": "Nos", "vilai": 8500.0, "variVizhukkaadu": 5.0, "thallupadi": 99.0, "thallupadiVagai": \"₹\"}]',
  },
];

/// Mock Coolie Receipts extracted from Firebase RTDB export.
const List<Map<String, dynamic>> mockCooliePatrugal = [
  {
    'againstInvoice': 'PVS-20, PVS-23, PVS-18, PVS-16, PVS-17, PVS-21',
    'amount': 90021.0,
    'clientAddress': 'திருச்சேறை, கும்பகோணம்',
    'clientName': 'சுந்தரி சில்க்ஸ் இந்தியா',
    'clientNameEn': 'Sundari Silks India',
    'date': '2026-06-08',
    'paymentMode': 'upi',
    'receiptNo': 'RCP/PVS/01',
    'referenceNo': '',
  },
  {
    'againstInvoice': 'VRM-105, VRM-106, VRM-111, VRM-107, VRM-104',
    'amount': 66333.0,
    'clientAddress': 'முள்ளிப்பட்டு, ஆரணி',
    'clientName': 'சுந்தரி சில்க்ஸ் இந்தியா',
    'clientNameEn': 'Sundari Silks India',
    'date': '2026-06-08',
    'paymentMode': 'cash',
    'receiptNo': 'RCP/VRM/01',
    'referenceNo': '',
  },
  {
    'againstInvoice': 'VRM-105, VRM-106, VRM-113, VRM-109',
    'amount': 55257.0,
    'clientAddress': 'முள்ளிப்பட்டு, ஆரணி',
    'clientName': 'சுந்தரி சில்க்ஸ் இந்தியா',
    'clientNameEn': 'Sundari Silks India',
    'date': '2026-06-08',
    'paymentMode': 'cash',
    'receiptNo': 'RCP/VRM/02',
    'referenceNo': '',
  },
  {
    'againstInvoice': 'PVS-22, PVS-23',
    'amount': 33393.0,
    'clientAddress': 'திருச்சேறை, கும்பகோணம்',
    'clientName': 'சுந்தரி சில்க்ஸ் இந்தியா',
    'clientNameEn': 'Sundari Silks India',
    'date': '2026-06-12',
    'paymentMode': 'bank_transfer',
    'receiptNo': 'RCP/PVS/18',
    'referenceNo': '',
  },
  {
    'againstInvoice': 'PVS-21',
    'amount': 15960.0,
    'clientAddress': 'திருச்சேறை, கும்பகோணம்',
    'clientName': 'சுந்தரி சில்க்ஸ் இந்தியா',
    'clientNameEn': 'Sundari Silks India',
    'date': '2026-05-23',
    'paymentMode': 'bank_transfer',
    'receiptNo': 'RCP/PVS/17',
    'referenceNo': '',
  },
];

/// Mock Silk Receipts extracted from Firebase RTDB export.
const List<Map<String, dynamic>> mockSilkPatrugal = [
  {
    'againstInvoice': 'SJPS-32',
    'amount': 77532.0,
    'clientAddress': '',
    'clientName': 'ஸ்ரீ சிவராம் சில்க் சாரீஸ்',
    'clientNameEn': 'Sri Sivaram Silk Sarees',
    'date': '2026-06-17',
    'paymentMode': 'bank_transfer',
    'receiptNo': 'RCP/SJPS/04',
    'referenceNo': '',
  },
  {
    'againstInvoice': 'SJPS-31',
    'amount': 52543303.0,
    'clientAddress': '',
    'clientName': 'ஸ்ரீ சிவராம் சில்க் சாரீஸ்',
    'clientNameEn': 'Sri Sivaram Silk Sarees',
    'date': '2026-06-11',
    'paymentMode': 'card',
    'receiptNo': 'RCP/SJPS/01',
    'referenceNo': '',
  },
  {
    'againstInvoice': 'SJPS-29',
    'amount': 139924.6,
    'clientAddress': '',
    'clientName': 'ஸ்ரீ சிவராம் சில்க் சாரீஸ்',
    'clientNameEn': 'Sri Sivaram Silk Sarees',
    'date': '2026-06-11',
    'paymentMode': 'cash',
    'receiptNo': 'RCP/SJPS/02',
    'referenceNo': '',
  },
  {
    'againstInvoice': 'SJPS-29, SJPS-31',
    'amount': 293055.0,
    'clientAddress': '',
    'clientName': 'ஸ்ரீ சிவராம் சில்க் சாரீஸ்',
    'clientNameEn': 'Sri Sivaram Silk Sarees',
    'date': '2026-06-11',
    'paymentMode': 'cash',
    'receiptNo': 'RCP/SJPS/03',
    'referenceNo': '',
  },
];
