package com.elvan.udukkai.localization.language_keys

import com.elvan.udukkai.core.navil.NavilMozhimaatri
import com.elvan.udukkai.localization.K

/**
 * Tamil translations.
 */
val ta: Map<String, String> = mapOf(
    K.make to "ஆக்கு",
    K.enCode to "ஆங்கிலம்",
    K.identifier to "அடையாளம்",
    K.loading to "ஏற்றுகிறது...",
    K.wideLogoOnly to "அகலமான ஓவுரு மட்டும்",
    K.verticalWideLogo to "செங்குத்து / அகலமான ஓவுரு",
    K.measurementMethod to "அளவீடு முறை",
    K.quantity to "அளவு",
    K.measureType to "அளவு வகை",
    K.authorizedSignatoryName to "அலுவல் கையொப்பத்தின் பெயர்",
    K.pincode to "அஞ்சல் குறியீடு",
    K.appName to "உடுக்கை",
    K.report to "அறிக்கை",
    K.reports to "அறிக்கைகள்",
    K.recentActivity to "நடப்பு வினைகள்",
    K.card to "அட்டை",
    K.erasing to "அழிக்கிறது...",
    K.appDataErased to "தரவு வெற்றிகரமாக அழிக்கப்பட்டது.",
    K.setharam to "சேதாரம்",
    K.wastage to "சேதாரம் (g)",
    K.unsavedDraftRestore to "சேமிக்காத வரைவு. மீட்டமைக்கவா?",
    K.backingUp to "சேமிக்கப்படுகிறது...",
    K.pendingSave to "சேமிப்பு நிலுவை",
    K.savedSuccessfully to "வெற்றிகரமாகச் சேமிக்கப்பட்டது",
    K.savedDetails to "சேமித்த தரவுகள்",
    K.aboutApp to "செயலி பற்றி",
    K.aboutAppDummy to "செயலி பற்றி (மாதிரி)",
    K.appVersionAndData to "செயலியின் பதிப்பு மற்றும் தரவுகள்",
    K.eraseAppData to "செயலித் தரவை அழி",
    K.logoutApplication to "செயலியிலிருந்து வெளியேறவும்.",
    K.billHeaderStyle to "ஓவுருவின் வடிவம்",
    K.smallLogoCompanyName to "சிறிய ஓவுரு + பெயர்",
    K.roundOff to "முழுமையாக்கம்",
    K.weight to "எடை",
    K.udukkaiApp to "உடுக்கை",
    K.elvanParthasarathy to "எல்வன் பார்த்தசாரதி",
    K.learnMoreAboutElvan to "எல்வன் பற்றி மேலும் அறிக",
    K.english to "ஆங்கிலம்",
    K.whichWorkspace to "எந்தச் செயல்முறை?",
    K.englishLanguage to "ஆங்கிலம்",
    K.showIfsc to "IFSC காட்டு",
    K.ifscCode to "IFSC குறியீடு",
    K.india to "இந்தியா",
    K.lastName to "இறுதிப்பெயர்",
    K.darkMode to "இருள் நிலை",
    K.cheque to "காசோலை",
    K.manage to "கையாளு",
    K.signatureStamp to "கையொப்பம்",
    K.accountNumber to "கணக்கு எண்",
    K.accountNoShort to "க/எ எண்",
    K.chargeName to "கட்டணப் பெயர்",
    K.branch to "கிளை",
    K.branchName to "கிளைப் பெயர்",
    K.courier to "கொரியர்",
    K.courierCharge to "கொரியர் (₹)",
    K.files to "கோப்புகள்",
    K.remarks to "குறிப்பு",
    K.shortCompanyName to "குறுகிய நிறுவனப் பெயர்",
    K.state to "மாநிலம்",
    K.searchState to "மாநிலம் தேடுக...",
    K.selectState to "மாநிலம் தேர்ந்தெடு",
    K.change to "மாற்று",
    K.mobile to "மாற்று பேசி எண்",
    K.district to "மாவட்டம்",
    K.scanAgain to "மீண்டும் தேடு",
    K.restoredSuccessfully to "வெற்றிகரமாக மீட்கப்பட்டது",
    K.recover to "மீட்கவும்",
    K.recycleBin to "மீட்பகம்",
    K.recycleBin30Days to "மீட்பகத்தில் உள்ளவை 30 நாள்களுக்குப் பிறகு தானாகவே அழிக்கப்படும்",
    K.recycleBinIsEmpty to "மீட்பகம் காலியானது",
    K.dataRestoredSuccessfully to "தரவு வெற்றிகரமாக மீட்டெடுக்கப்பட்டது!",
    K.email to "மின்னஞ்சல்",
    K.emailAddress to "மின்னஞ்சல் முகவரி",
    K.enterEmail to "மின்னஞ்சலை உள்ளிடவும்",
    K.confirmEmail to "மின்னஞ்சலை உறுதிசெய்க",
    K.totalWeight to "மொத்த எடை",
    K.total to "மொத்தம்",
    K.totals to "மொத்தங்கள்",
    K.firstName to "முதற்பெயர்",
    K.done to "முடிந்தது",
    K.home to "முகப்பு",
    K.address to "முகவரி",
    K.companyAddressDetails to "நிறுவன முகவரித் தரவுகள்",
    K.advance to "முன்தொகை",
    K.proforma to "முன்வரைவு",
    K.country to "நாடு",
    K.dismiss to "நிராகரி",
    K.deletePermanently to "நிரந்தரமாக அழி",
    K.udukkai to "உடுக்கை",
    K.tapGetStarted to "உடுக்கையைத் தொடங்க கீழ் உள்ள பொத்தானைத் தட்டவும்",
    K.company to "நிறுவனம்",
    K.companyDetail to "நிறுவனத் தரவு",
    K.companies to "நிறுவனங்கள்",
    K.companyLogo to "நிறுவனத்தின் ஓவுரு",
    K.companyName to "நிறுவனத்தின் பெயர்",
    K.selectCompany to "நிறுவனத்தைத் தேர்ந்தெடு",
    K.lightMode to "ஒளி நிலை",
    K.themeLightDarkAuto to "ஒளி இருள் தானியங்கு",
    K.violet to "ஊதா",
    K.city to "ஊர்",
    K.security to "பாதுகாப்பு",
    K.green to "பச்சை",
    K.selectImageSource to "படத்தின் மூலத்தைத் தேர்ந்தெடுக்கவும்",
    K.upload to "பதிவேற்று",
    K.phone to "பேசி எண்",
    K.phoneNumbers to "பேசி எண்கள்",
    K.user to "பயனர்",
    K.userNameGreetingDesc to "இப்பெயர் முகப்புத்திரையில் தோன்றும்.",
    K.storageUsed to "பயன்படுத்திய சேமிப்பு",
    K.restorePreviousDataPrompt to "பழைய தரவை மீட்டெடுக்கவா?",
    K.oldDataAvailable to "பழைய தரவு கிடைக்கிறது",
    K.pdfTheme to "PDF தோற்றம்",
    K.grandTotal to "மொத்தத் தொகை",
    K.billedTo to "பெறுநர்",
    K.nameAlreadyExists to "இப்பெயர் ஏற்கனவே உள்ளது.",
    K.enterName to "பெயரை உள்ளிடுக",
    K.other to "பிற",
    K.addOtherCharges to "பிற கட்டணம் சேர்",
    K.dateOfBirth to "பிறந்த தேதி",
    K.createRecord to "புதிய ஆக்கம்",
    K.addNew to "புதிய சேர்க்கை",
    K.camera to "புகைப்படக் கருவி",
    K.gallery to "புகைப்படத் தொகுப்பு",
    K.tamilCode to "தமிழ்",
    K.tamil to "தமிழ்",
    K.thamizhLatin to "தமிழ் இலத்தீன்",
    K.autoGenerated to "தானியங்கி",
    K.autoGeneratedOnSave to "சேமிக்கையில் தானே உருவாகும்",
    K.search to "தேடுக...",
    K.select to "தேர்ந்தெடு",
    K.discShort to "த.படி",
    K.taCode to "தமிழ்",
    K.tamilEnglishAuto to "தமிழ், ஆங்கிலம், தானியங்கு",
    K.restoringData to "தரவை மீட்டெடுக்கிறது...",
    K.permanentlyEraseData to "தரவுகளை முற்றிலும் அழிக்கவும்.",
    K.detailsSavedSuccessfully to "தரவுகள் வெற்றிகரமாக சேமிக்கப்பட்டன",
    K.enterCompanyDetails to "தரவுகளை உள்ளிடுக",
    K.seedAppDev to "தரவுகளை உருவாக்கு (உருவாக்குனர்)",
    K.activeCompany to "தற்போதைய நிறுவனம்",
    K.display to "திரை",
    K.contactAndTax to "தொடர்பு & வரி",
    K.amountMustBeGreaterThanZero to "தொகை 0-ஐ விட மிகுதியாக இருக்க வேண்டும்",
    K.amountRequired to "தொகை *",
    K.telephone to "தொலைப்பேசி",
    K.subtotal to "இடைமொத்தம்",
    K.selectYourWorkspace to "உங்கள் செயல்முறையைத் தேர்ந்தெடுக்கவும்",
    K.devErase to "உருவாக்குனர்: தரவுகளை அழி",
    K.devSeed to "உருவாக்குனர்: தரவுகளை உருவாக்கு",
    K.clientNameSearch to "வாங்குநர் பெயர்",
    K.businessDetails to "வாங்குநர் தரவுகள்",
    K.vanakkam to "வணக்கம்!",
    K.draft to "வரைவு",
    K.restoreDraftPrompt to "வரைவு மீட்கவா?",
    K.taxCollected to "வரி திரட்டியவை",
    K.placeOfSupply to "வழங்கல் இடம்",
    K.fullAddress to "முழு முகவரி",
    K.signOutPrompt to "வெளியேற வேண்டுமா?",
    K.logout to "வெளியேறு",
    K.signingOut to "வெளியேறுகிறது...",
    K.signedOutSuccessfully to "வெற்றிகரமாக வெளியேற்றப்பட்டது",
    K.fillAllFields to "விடுபட்ட புலங்களை நிரப்பவும்.",
    K.sellingRate to "விற்பனை விலை",
    K.pricingAndTax to "விலை மற்றும் வரி",
    K.rate to "விலை",
    K.loginToAccessApp to "செயலியை அணுக உள்நுழையவும்",
    K.password to "கடவுச்சொல்",
    K.enterPassword to "கடவுச்சொல்லை உள்ளிடவும்",
    K.welcomeToUdukkai to "உடுக்கைக்கு நல்வரவு",
    K.companyProfile to "நிறுவனத் தன்னுரு",
    K.selectCompanyProfile to "நிறுவனத்தைத் தேர்ந்தெடு",
    K.maxFiveProfiles to "பெருமளவு 5 தன்னுருக்கள் மட்டுமே",
    K.addNewProfile to "புதிய தன்னுரு சேர்",
    K.createNewProfile to "புதிய தன்னுருவை உருவாக்கு",
    K.profileSaved to "தன்னுரு சேமிக்கப்பட்டது!",
    K.profileDeleted to "தன்னுரு நீக்கப்பட்டது",
    K.noSavedProfiles to "தன்னுருக்கள் இல்லை",
    K.deleteCompanyProfilePrompt to "தன்னுருவை முற்றிலும் நீக்கவா?",
    K.signIn to "உள்நுழைக",
    K.selectAllBtn to "அனைத்தையும் தேர்",
    K.seeAllBtn to "யாவும்",
    K.clear to "அழிக்க",
    K.saveBtn to "சேமி",
    K.add to "சேர்",
    K.addBtn to "சேர்",
    K.okBtn to "சரி",
    K.backupNowBtn to "காப்பு செய்",
    K.cancelBtn to "கைவிடு",
    K.editRecord to "மாற்றியமை",
    K.restoreBtn to "மீட்டெடு",
    K.restoreDataBtn to "மீட்டெடு",
    K.deleteBtn to "நீக்கு",
    K.syncAppBtn to "செயலியை ஒருங்கிணை",
    K.saveUserBtn to "சேமி",
    K.addProductBtn to "பொருளைச் சேர்",
    K.newReceiptBtn to "புதிய பற்றுச்சீட்டு",
    K.newInvoiceBtn to "புதிய பட்டியல்",
    K.startFreshBtn to "புதியதாக தொடங்கு",
    K.discardBtn to "புறக்கணி",
    K.customBtn to "தனிப்பயன்",
    K.eraseDataBtn to "தரவை அழி",
    K.getStartedBtn to "தொடங்குக",
    K.continueBtn to "தொடர்",
    K.continueText to "தொடரவும்",
    K.createBtn to "உருவாக்கு",
    K.signOutBtn to "வெளியேறு",
    K.tagline to "அடைமொழி",
    K.settings to "அமைப்புகள்",
    K.database to "சேமிப்பு",
    K.storageAndBackup to "சேமிப்பு & காப்பு",
    K.appSettings to "செயலி அமைப்புகள்",
    K.appLanguage to "செயலி மொழி",
    K.noBackupYet to "இதுவரை காப்பு இல்லை",
    K.secondaryLanguage to "இரண்டாம் மொழி",
    K.bilingualMode to "இருமொழி முறை",
    K.backup to "காப்பு",
    K.noBackupFound to "காப்புத் தரவு இல்லை, புதிதாக தொடங்குகிறது.",
    K.backupFound to "காப்புத் தரவு கிடைத்தது!",
    K.checkingForBackups to "காப்புத் தரவு தேடப்படுகிறது...",
    K.lastAutoBackup to "கடைசி தானியக்கக் காப்பு",
    K.language to "மொழி",
    K.languageInfo to "மொழி மாற்றம் அனைத்துப் பக்கங்கள், வழிசெலுத்தல் மற்றும் அமைப்புகளிலும் உடனடியாக நடைமுறைப்படுத்தப்படும்.",
    K.selectLanguage to "மொழியைத் தேர்ந்தெடு",
    K.primaryLanguage to "முதன்மை மொழி",
    K.companySettings to "நிறுவன அமைப்புகள்",
    K.syncRecentChanges to "அண்மை மாற்றங்களை ஒத்திசைக்கவும்.",
    K.synced to "ஒருங்கிணைக்கப்பட்டது!",
    K.syncing to "ஒருங்கிணைக்கிறது...",
    K.userSettings to "பயனர் அமைப்புகள்",
    K.pdfStylingOptions to "PDF வடிவமைப்பு விருப்பங்கள்",
    K.systemAuto to "தானியங்கி அமைப்பு",
    K.syncLogoutClearData to "ஒருகிணை, வெளியேறு, தரவு அழி",
    K.backupDatabase to "தரவு காப்பு",
    K.backupData to "தரவு காப்பு செய்",
    K.backupSavedToDocuments to "தரவு ஆவணங்களில் சேமிக்கப்பட்டது.",
    K.databaseStore to "தரவுத்தளம்",
    K.manageDatabasesBackups to "தரவுத்தளங்கள் & காப்பைக் கையாளு",
    K.manuallyUpdateBackup to "உங்கள் தரவை சேமிக்கவும்.",
    K.choosePreferredLanguage to "விருப்பமான மொழியைத் தேர்வு செய்க",
    K.deletedProducts to "அழிக்கப்பட்ட பொருள்கள்",
    K.deletedCustomers to "அழிக்கப்பட்ட வாங்குநர்கள்",
    K.deletedInvoices to "அழிக்கப்பட்ட பட்டியல்கள்",
    K.deletedReceipts to "அழிக்கப்பட்ட பற்றுச்சீட்டுகள்",
    K.hsnSacCode to "HSN/SAC குறியீடு",
    K.addAtLeastOneProduct to "குறைந்தது ஒரு பொருள் சேர்",
    K.softwareDesigner to "மென்பொருள் வடிவாளர்",
    K.aboutDeveloper to "மென்பொருள் வடிவாளர் பற்றி",
    K.aboutDeveloperDummy to "மென்பொருள் வடிவாளர் பற்றி (மாதிரி)",
    K.invoiceNoCustomerPlaceholder to "பட்டியல் எண் / வாங்குநர்...",
    K.product to "பொருள்",
    K.productDeleted to "பொருள் அழிக்கப்பட்டது",
    K.productSavedSuccessfully to "பொருள் சேமிக்கப்பட்டது",
    K.productNameRequired to "பொருள் பெயர் தேவை",
    K.productDetails to "பொருள் தரவுகள்",
    K.addFirstProduct to "முதல் பொருளைச் சேர்க்கவும்",
    K.noProductsYet to "பொருட்கள் இல்லை",
    K.products to "பொருட்கள்",
    K.customer to "வாங்குநர்",
    K.customerDeleted to "வாங்குநர் அழிக்கப்பட்டது",
    K.customerSavedSuccessfully to "வாங்குநர் சேமிக்கப்பட்டது",
    K.customerName to "வாங்குநர் பெயர்",
    K.customerNameRequired to "வாங்குநர் பெயர் தேவை",
    K.addFirstCustomer to "முதல் வணிகரைச் சேர்க்கவும்",
    K.selectCustomer to "வணிகரைத் தேர்ந்தெடு",
    K.addCustomer to "வணிகரைச் சேர்",
    K.customers to "வாங்குநர்கள்",
    K.noCustomersYet to "வாங்குநர்கள் இல்லை",
    K.ahimsaSilk to "அகிம்சைப் பட்டு",
    K.ahimsaSilkAmount to "அகிம்சைப் பட்டு (₹)",
    K.forWhichInvoice to "எந்தப் பட்டியலுக்கு",
    K.gstRate to "GST வீதம் %",
    K.gstin to "GSTIN",
    K.invalidGstinFormat to "GSTIN வடிவம் தவறானது",
    K.gstinTaxId to "GSTIN / வரி அடையாள எண்",
    K.forGstInvoice to "வழக்கமான GST பட்டியல்களுக்குப் பயன்படுத்தப்படும்.",
    K.showGstSplitsInTable to "GST பிரிப்புகளைக் காட்டு",
    K.coolieHomePage to "கூலி முகப்புப் பக்கம்",
    K.coolieCompanyBranding to "கூலி நிறுவன அடையாளங்கள்",
    K.coolieCompanyName to "கூலி நிறுவனப் பெயர்",
    K.coolieData to "கூலித் தரவுகள்",
    K.totalInvoiced to "மொத்தத் தொகை",
    K.totalInvoices to "மொத்தப் பட்டியல்கள்",
    K.globalDiscount to "முழுத் தள்ளுபடி",
    K.udukkaiCoolie to "உடுக்கைக் கூலி",
    K.udukkaiSilk to "உடுக்கைப் பட்டு",
    K.invoice to "பட்டியல்",
    K.invoiceNumber to "பட்டியல் எண்",
    K.invoiceCount to "பட்டியல் எண்ணிக்கை",
    K.billNo to "பட்டியல் எண்",
    K.selectPrimaryBillingLanguage to "பட்டியல் முதன்மொழி",
    K.customerDetailsAutoFilledAfterInvoice to "பட்டியலைத் தேர்ந்தெடுத்ததும் வாங்குநர் தரவுகள் தானே நிரப்பப்படும்.",
    K.invoiceDetails to "பட்டியல் தரவுகள்",
    K.invoiceType to "பட்டியல் வகை",
    K.selectInvoice to "பட்டியலைத் தேர்ந்தெடு",
    K.invoices to "பட்டியல்கள்",
    K.selectInvoices to "பட்டியல்களைத் தேர்ந்தெடு",
    K.billingGstSorted to "உங்கள் பட்டியல்கள் & GST, எளிதாக்கப்பட்டது.",
    K.whichBillingLanguagePrompt to "பட்டியலில் எம்மொழியை பயன்படுத்த வேண்டும்?",
    K.silkHomePage to "பட்டு முகப்புப் பக்கம்",
    K.silkCompanyBranding to "பட்டு நிறுவன அடையாளங்கள்",
    K.silkData to "பட்டுத் தரவுகள்",
    K.newBill to "புதிய பட்டியல்",
    K.discount to "தள்ளுபடி",
    K.gstReturn to "வரி அறிக்கை",
    K.gstReturns to "வரி அறிக்கைகள்",
    K.taxInvoice to "வரிப் பட்டியல்",
    K.paymentDetails to "கட்டணத் தரவு",
    K.selectPaymentMode to "கட்டண முறையைத் தேர்ந்தெடு",
    K.paymentModeRequired to "கட்டண முறை *",
    K.cash to "காசு",
    K.bankDetails to "வங்கித் தரவுகள்",
    K.coolieReceiptEditor to "கூலிப் பற்றுச்சீட்டு திருத்தி",
    K.usedForCoolieBillsReceipts to "கூலி பட்டியல்கள் மற்றும் பற்றுச்சீட்டுகளுக்குப் பயன்படுத்தப்படும்.",
    K.receipt to "பற்றுச்சீட்டு",
    K.receiptSaved to "பற்றுச்சீட்டு சேமிக்கப்பட்டது",
    K.receiptNumber to "பற்றுச்சீட்டு எண்",
    K.receiptNumberAlreadyExists to "பற்றுச்சீட்டு எண் ஏற்கனவே உள்ளது!",
    K.receiptCount to "பற்றுச்சீட்டு எண்ணிக்கை",
    K.receiptDate to "பற்றுச்சீட்டு நாள்",
    K.receiptDetails to "பற்றுச்சீட்டுத் தரவுகள்",
    K.receiptType to "பற்றுச்சீட்டு வகை",
    K.receipts to "பற்றுச்சீட்டுகள்",
    K.invoiceReceiptLanguage to "பட்டியல் & பற்றுச்சீட்டு மொழி",
    K.silkReceiptEditor to "பட்டுப் பற்றுச்சீட்டு திருத்தி",
    K.newCoolieReceipt to "புதிய கூலிப் பற்றுச்சீட்டு",
    K.newSilkReceipt to "புதிய பட்டுப் பற்றுச்சீட்டு",
    K.bank to "வங்கி",
    K.bankTransfer to "வங்கிப் பரிமாற்றம்",
    K.showBankDetails to "வங்கித் தரவு காட்டு",
    K.bankName to "வங்கியின் பெயர்",
    K.august to "ஆகஸ்ட்",
    K.april to "ஏப்ரல்",
    K.october to "அக்டோபர்",
    K.wednesday to "அறிவன்",
    K.tuesday to "செவ்வாய்",
    K.december to "டிசம்பர்",
    K.janShort to "ஜன",
    K.febShort to "ஃபிப்",
    K.marShort to "மார்",
    K.aprShort to "ஏப்",
    K.mayShort to "மே",
    K.junShort to "ஜூன்",
    K.julShort to "ஜூலை",
    K.augShort to "ஆக",
    K.sepShort to "செப்",
    K.octShort to "அக்",
    K.novShort to "நவ",
    K.decShort to "டிச",
    K.february to "ஃபிப்ரவரி",
    K.january to "ஜனவரி",
    K.july to "ஜூலை",
    K.june to "ஜூன்",
    K.saturday to "காரி",
    K.march to "மார்ச்",
    K.may to "மே",
    K.am to "முற்பகல்",
    K.date to "நாள்",
    K.november to "நவம்பர்",
    K.sunday to "ஞாயிறு",
    K.pm to "பிற்பகல்",
    K.september to "செப்டம்பர்",
    K.monday to "திங்கள்",
    K.friday to "வெள்ளி",
    K.thursday to "வியாழன்",
    K.couldNotSavePrefix to "சேமிக்க இயலவில்லை:",
    K.none to "இல்லை",
    K.noSignature to "கையொப்பம் இல்லை",
    K.referenceOrTxnNo to "குறிப்பு எண் / பரிமாற்ற எண்",
    K.deletePermanentlyConfirm to "நிரந்தரமாக அழிக்கவா? மீட்க இயலாது.",
    K.enterAllRequiredCompanyNames to "தேவையான அனைத்து நிறுவனப் பெயர்களையும் உள்ளிடுக.",
    K.noLogo to "ஓவுரு இல்லை",
    K.noReceiptsYet to "பற்றுச்சீட்டுகள் இல்லை",
    K.noInvoicesYet to "பட்டியல்கள் இல்லை",
    K.error to "பிழை",
    K.udukkaiBrand to "உடுக்கை",
    K.udukkaiCoolieBrand to "உடுக்கைக் கூலி",
    K.udukkaiSilkBrand to "உடுக்கைப் பட்டு",
    K.coolie to "உடுக்கைக் கூலி",
    K.silk to "உடுக்கைப் பட்டு",
    K.themeLightMode to "ஒளி நிலை",
    K.back to "பின்கட்டளை",
    K.more to "மேலும்",
    K.appearance to "தோற்றம்",
    K.about to "குறித்து",
    K.unit to "அலகு",
    K.amount to "தொகை",
    K.header to "தலைப்பு",
    K.noData to "தரவு இல்லை",
    K.edit to "திருத்து",
    K.save to "சேமி",
    K.delete to "அழி",
    K.cancel to "கைவிடு",
    K.confirm to "உறுதிசெய்",
    K.signOutConfirmPrompt to "வெளியேற வேண்டுமா?",
    K.pureTamil to "செந்தமிழ்",
    K.elvanSansFont to "எல்வன் சான்ஸ்",
    K.fontFamily to "எழுத்துரு",
    K.navilSans to "நவில் சான்ஸ்",
    K.elvanSans to "எல்வன் சான்ஸ்",
    K.navilSansDesc to "இயல்புநிலை (Apple SF Tamil + SF Pro)",
    K.elvanSansDesc to "எல்வன் சான்ஸ் எழுத்துரு",
    K.fontUpdatedSuccessfully to "எழுத்துரு மாற்றப்பட்டது",
    K.pureTamilPolicy to "தூய தமிழ் கொள்கை",
    K.dataRepository to "தரவு காப்பகம்",
    K.version to "பதிப்பு",
    K.elvanNavil to "எல்வன் நவில்",
    K.aboutElvanNavil to "எல்வன் நவில்",
    K.elvanNavilStudioDesc to "இச்செயலின் கடைப்பிடியான நிறுவனம்",
    K.allRightsReserved to "© அனைத்து உரிமைகளும் காக்கப்பட்டவை",
    K.navilMozhimatri to "நவில் மொழிமாற்றி",
    K.navilMozhimatriDesc to "தொல்காப்பிய ஒலிபெயர்ப்புப் பொறி",
    K.tamilInput to "தமிழ் உள்ளீடு",
    K.navilOutput to "நவில் வெளியீடு",
    K.syllableBreakdown to "அசை பிரித்தல்",
    K.copiedToClipboard to "படியெடுக்கப்பட்டது",
    K.testPresets to "எடுத்துக்காட்டுகள்",
    K.tolkappiyamRules to "தொல்காப்பிய நெறிகள்",
    K.characters to "எழுத்துகள்",
    K.words to "சொற்கள்",
    K.printBtn to "அச்சிடு",
    K.storagePermissionRequired to "சேமிப்பக அனுமதி தேவை",
    K.storagePermissionDesc to "காப்புப்பிரதி மற்றும் பட்டியல்களைச் சேமிக்க இந்த அனுமதி தேவை.",
    K.grantPermissionBtn to "அனுமதி வழங்கு",
    K.all to "யாவும்",
)

/**
 * Dynamically generated Tamil Latin (Tanglish/Romanized) translations
 * using the pure Kotlin Tolkappiyam NavilEngine.
 * Eliminates the need for a separate static TaLatn.kt file.
 */
val taLatn: Map<String, String> by lazy {
    ta.mapValues { (_, tamilText) ->
        NavilMozhimaatri.transliterate(tamilText)
    }
}
