const Map<String, String> en = {
  // ── Core / Common ──
  'aakku': 'Make',
  'aangilam': 'en',
  'adaiyaalam': 'Identifier',
  'aetrugiradhu': 'Loading...',
  'agalamaanaOavuruMattum': 'Wide Logo Only',
  'agalamaanaoavuru': 'Vertical / Wide Logo',
  'alaveeduMurai': 'Measurement Method',
  'alavu': 'Quantity',
  'alavuVagai': 'Measure Type',
  'aluvalkaiyoppam': 'Authorized Signatory Name',
  'anjalKuriyeedu': 'Pincode',
  'appPeyar': 'Elvan Niril',
  'arikkai': 'Report',
  'arikkaigal': 'Reports',
  'arugilSeyalgal': 'Recent Activity',
  'attai': 'Card',
  'azhikkiradhu': 'Erasing...',
  'azhippuvetri': 'App data erased.',
  'chaedhaaram': 'Setharam',
  'chaedhaaramGiraam': 'Wastage',
  'chaemikkaadhaVaraivu': 'Unsaved draft. Restore?',
  'chaemikkappadugiradhu': 'Backing up...',
  'chaemippuNiluvai': 'Pending Save',
  'chaemippuvetri': 'Saved successfully',
  'chaemiththaTharavugal': 'Saved Details',
  'cheyaliPatri': 'About App',
  'cheyaliPatriMaadhiri': 'About App (Dummy)',
  'cheyalipadhippu': 'App version and data',
  'cheyalithTharavaiAzhi': 'Erase App Data',
  'cheyaliyilirundhuVeliyaeravum': 'Logout from the application.',
  'chinnathinVadivam': 'Bill Header Style',
  'chiriyaOavuruPeyar': 'Small Logo + Company Name',
  'chuttruOppu': 'Round Off',
  'edai': 'Weight',
  'elvanNiril': 'Elvan Niril',
  'elvanParthasarathy': 'Elvan Parthasarathy',
  'elvanPatriMaelumAriga': 'Learn more about Elvan',
  'endhachCheyalmurai': 'Which workspace?',
  'ifscKaattu': 'Show IFSC',
  'ifscKuriyeedu': 'IFSC Code',
  'india': 'India',
  'irudhiPeyar': 'Last Name',
  'irulNilai': 'Dark Mode',
  'kaasoalai': 'Cheque',
  'kaiyaalu': 'Manage',
  'kaiyoppam': 'Signature / Stamp',
  'kanakkuEn': 'Account Number',
  'kanakkuKuriyeedu': 'A/C No',
  'kattanaPeyar': 'Charge Name',
  'kilai': 'Branch',
  'kilaipPeyar': 'Branch Name',
  'koriyar': 'Courier',
  'koriyarKattanam': 'Courier (₹)',
  'kurippu': 'Remarks',
  'kurugiyaNiruvanaPeyar': 'Short Company Name',
  'maanilam': 'State',
  'maanilamThaedu': 'Search state...',
  'maanilamThaerodhu': 'Select State',
  'maatru': 'Change',
  'maatruPaesiEn': 'Mobile',
  'maavattam': 'District',
  'meendumThaedu': 'Scan Again',
  'meeteduppuVetri': 'Restored successfully',
  'meetkavum': 'Recover',
  'meetpagam': 'Recycle Bin',
  'meetpagam30Naal': 'Items in the recycle bin will be automatically deleted after 30 days',
  'meetpagamKaaliyanadhu': 'Recycle bin is empty',
  'meetteduppuvetri': 'Data restored successfully!',
  'minnanjal': 'Email',
  'minnanjalMugavari': 'Email Address',
  'minnanjalaiUllidavum': 'Enter your email',
  'minnanjalaiUrudhiseiga': 'Confirm Email',
  'mothaEdai': 'Total Weight',
  'motham': 'Total',
  'mothangal': 'Totals',
  'mudhalPeyar': 'First Name',
  'mudindhadhu': 'Done',
  'mugappu': 'Home',
  'mugavari': 'Address',
  'mugavaritharavugal': 'Company address details',
  'munthogai': 'Advance',
  'munvaraivu': 'Proforma',
  'naadu': 'Country',
  'niraagari': 'Dismiss',
  'nirandharaAzhippu': 'Delete Permanently',
  'niril': 'Niril',
  'nirilthodanga': 'Tap "Get Started" to continue with Niril.',
  'niruvanam': 'Company',
  'niruvanathTharavu': 'Company Detail',
  'niruvanangal': 'Companies',
  'niruvanathinOavuru': 'Company Logo',
  'niruvanathinPeyar': 'Company Name',
  'niruvanaththaithThaernhedu': 'Select Company',
  'oliNilai': 'Light Mode',
  'olirIrulThaaniyangu': 'Light mode, Dark mode, Auto',
  'oodhaa': 'Violet',
  'oor': 'City',
  'paadhugaappu': 'Security',
  'pachai': 'Green',
  'padammoolam': 'Select Image Source',
  'padhivaetru': 'Upload',
  'paesiEn': 'Phone',
  'paesiEnkal': 'Phone Numbers',
  'payanar': 'User',
  'payanarVilakkam': 'This name will appear on the home screen greeting.',
  'payanpaduthiyaChaemippu': 'Storage Used',
  'pazhaiyaTharavaiMeettedukkavaa': 'Your previous data was found. Would you like to restore it?',
  'pazhaiyaTharavuKidaikkiradhu': 'Old data available',
  'pdfThoatram': 'PDF Theme',
  'perumMotham': 'Grand Total',
  'perunar': 'Billed To',
  'peyarEarkanavaeUlladhu': 'This name already exists.',
  'peyaraiUlliduga': 'Enter name',
  'pira': 'Other',
  'piraVarivuChaer': 'Add Other Charges',
  'pirandhaThaedhi': 'Date of Birth',
  'pudhiyaAakkam': 'Create',
  'pudhiyaChaerkkai': 'Add New',
  'pugaippadakKaruvi': 'Camera',
  'pugaippadathThoguppu': 'Gallery',
  'tamil': 'Tamil',
  'english': 'English',
  'tamilLatin': 'Thamizh Latin',
  'thaaniyangki': 'Auto-generated',
  'thaaniyangkiUruvaam': 'Auto-generated on save',
  'thaeduga': 'Search...',
  'thaerndhedu': 'Select',
  'thallupadiChurukkam': 'Disc',
  'thamizh': 'ta',
  'thamizhAangilamThaaniyangu': 'Tamil, English, Auto',
  'tharavaiMeettedukkiradhu': 'Restoring data...',
  'tharavaiazhi': 'Permanently erase data.',
  'tharavugalChaemippuVetri': 'Details saved successfully',
  'tharavugalaiUlliduga': 'Enter Company Details',
  'tharavugalaiUruvaakkuUruvaakkunar': 'Seed App (Dev)',
  'tharpoadhaiyaNiruvanam': 'Active Company',
  'thirai': 'Display',
  'thodarpuVari': 'Contact & Tax',
  'thogaiChuzhiyaththaiVidaMigudhiyaagaIrukkaVaendum': 'Amount must be greater than 0',
  'thogaiVinmeen': 'Amount *',
  'tholaipaesi': 'Phone',
  'ulmotham': 'Subtotal',
  'ungalCheyalmuraiyaithThaerndhedukkavum': 'Select your workspace',
  'uruvaakkunarTharavugalaiAzhi': 'Dev: Erase',
  'uruvaakkunarTharavugalaiUruvaakku': 'Dev: Seed',
  'vaangunarPeyarThaedu': 'Client Name',
  'vaangunarTharavugal': 'Business Details',
  'vanakkam': 'Vanakkam!',
  'varaivu': 'Draft',
  'varaivuMeetka': 'Restore draft?',
  'variThirattiyavai': 'Tax Collected',
  'vazhangalIdam': 'Place of Supply',
  'velinaadMugavari': 'Full Address',
  'veliyaeraVaendumaa': 'Sign Out?',
  'veliyaeru': 'Logout',
  'veliyaerugiradhu': 'Signing out...',
  'veliyaetramvetri': 'Signed out successfully',
  'vidupattaPulangalaiNirappavum': 'Please fill in all fields.',
  'vilai': 'Selling Rate',
  'vilaiMatrumVari': 'Pricing & Tax',
  'vilaiVeedham': 'Rate',

  // ── Authentication & Onboarding ──
  'cheyaliyaiAnugaUlnuzhaiyavum': 'Login to access your app',
  'kadavuchol': 'Password',
  'kadavuchollaiUllidavum': 'Please enter your password',
  'nirilirkuNalvaravu': 'Welcome to Niril',
  'niruvanaThannuru': 'Company Profile',
  'niruvanamThaerodhu': 'Select a company profile',
  'perumalavu5thannuru': 'Maximum 5 profiles allowed',
  'pudhiyaThannuruChaer': 'Add New Profile',
  'pudhiyaThannuruvaiUruvaakku': 'Create New Profile',
  'thannuruChaemikkappattadhu': 'Profile saved!',
  'thannuruNeekkappattadhu': 'Profile deleted',
  'thannurukkalIllai': 'No saved profiles yet',
  'thannuruvaiMutrilumNeekkavaa': 'Permanently delete this company profile?',
  'ulnuzhaiga': 'Sign In',

  // ── Navigation & Actions (Buttons) ──
  'anaithaiyumTheriPtn': 'Select All',
  'anaiththaiyumPaarPtn': 'See All',
  'azhikka': 'Clear',
  'chaemiPtn': 'Save',
  'chaer': 'Add',
  'chaerPtn': 'Add',
  'chariPtn': 'OK',
  'kaappuCheiPtn': 'Backup Now',
  'kaividuPtn': 'Cancel',
  'maatriyamai': 'Edit',
  'meeteduppuCheiPtn': 'Restore',
  'meetteduPtn': 'Restore Data',
  'neekkuPtn': 'Delete',
  'orunginaiCheyaliPtn': 'Sync App',
  'payanarTharavugalaiMaetriduPtn': 'Save',
  'porulaichChaerPtn': 'Add Product',
  'pudhiyaPatrucheettuPtn': 'New Receipt',
  'pudhiyaPattiyalPtn': 'New Invoice',
  'pudhiyadhaagaThodanguPtn': 'Start Fresh',
  'purakkaniPtn': 'Discard',
  'thanipPayanPtn': 'Custom',
  'tharavaiAzhiPtn': 'Erase Data',
  'thodangugaPtn': 'Get Started',
  'thodarPtn': 'Continue',
  'thodaravum': 'Continue',
  'uruvaakkuPtn': 'Create',
  'veliyaeruPtn': 'Sign Out',

  // ── Settings & Backup ──
  'adaimozhi': 'Tagline',
  'amaippugal': 'Settings',
  'chaemippu': 'Database',
  'chaemippuMatrumKaappu': 'Storage & Backup',
  'cheyaliAmaippugal': 'App Settings',
  'cheyaliMozhi': 'App Language',
  'idhuvuraiKaappuIllai': 'No Backup Yet',
  'irandaamMozhi': 'Secondary Language',
  'irumozhiMurai': 'Bilingual Mode',
  'kaappu': 'Backup',
  'kaapputhTharavuIllai': 'No backup found, starting fresh.',
  'kaapputhTharavuKidaithadhu': 'Backup found!',
  'kaapputhTharavuThaedal': 'Checking for backups...',
  'kadaisiThaaniyakkaKaappu': 'Last Auto-Backup',
  'language': 'Language',
  'mozhiThaervu': 'Select Language',
  'mudhanmaiMozhi': 'Primary Language',
  'niruvanaAmaippugal': 'Company Settings',
  'orunginaiCheyaliVilakkam': 'Sync recent changes.',
  'orunginaikkappattadhu': 'Synced!',
  'orunginaikkiRadhu': 'Syncing...',
  'payanarAmaippugal': 'User Settings',
  'pilVadivamaippuViruppangal': 'PDF styling options',
  'thaaniyangiAmaippu': 'System Auto',
  'thaekkagathaiazhi': 'Sync, Logout, Clear Data',
  'tharavuKaappu': 'Backup Database',
  'tharavuKaappuChei': 'Backup Data',
  'tharavuchaemippuvetri': 'Backup successfully saved to Documents.',
  'tharavuthalam': 'Database',
  'tharavuthalangalKaappaikKaiyaalu': 'Manage databases and backups',
  'ungalTharavaiChaemikkavum': 'Manually update your backup file.',
  'viruppaMozhiThaervu': 'Choose your preferred language',

  // ── Entities (Customer, Product) ──
  'azhikkappattaPorulgal': 'Deleted Products',
  'azhikkappattaVaangunargal': 'Deleted Customers',
  'hsnSacKuriyeedu': 'HSN/SAC Code',
  'kuriaindhOruPorul': 'Add at least one product',
  'menporulVadivaalar': 'Software Designer',
  'menporulVadivaalarPatri': 'About Developer',
  'menporulVadivaalarPatriMaadhiri': 'About Developer (Dummy)',
  'pattiyalEnVaangunar': 'Invoice No / Customer...',
  'porul': 'Product',
  'porulAzhikkappattadhu': 'Product deleted',
  'porulChaemikkappattadhu': 'Product saved successfully',
  'porulPeyarThaevai': 'Product name is required',
  'porulTharavugal': 'Product Details',
  'porulaiChaerkkavum': 'Add your first product',
  'porulgalIllai': 'No products yet',
  'porutkal': 'Products',
  'vaangunar': 'Customer',
  'vaangunarAzhikkappattadhu': 'Customer deleted',
  'vaangunarChaemikkappattadhu': 'Customer saved successfully',
  'vaangunarPeyar': 'Customer Name',
  'vaangunarPeyarThaevai': 'Customer name is required',
  'vaangunaraiChaerkkavum': 'Add your first customer to get started',
  'vaangunaraiThaerodhu': 'Select a customer',
  'vaangunaraichChaer': 'Add Customer',
  'vaangunargal': 'Customers',
  'vaangunargalIllai': 'No customers yet',

  // ── Invoicing & Billing (Pattiyal) ──
  'ahimsaiPattu': 'Ahimsa Silk',
  'ahimsaiPattuThogai': 'Ahimsa Silk (\u20b9)',
  'endhapPattiyalukku': 'For which invoice?',
  'gstVeedham': 'GST Rate %',
  'gstin': 'GSTIN',
  'gstinTavaru': 'Invalid GSTIN format',
  'gstinVariAdaiyaalaEn': 'GSTIN / Tax ID',
  'gstpattiyalukku': 'Used for regular GST invoices.',
  'gstpirippugal': 'Show GST splits in table',
  'kooliMugappupPakkam': 'Coolie Home Page',
  'kooliNiruvanaAdaiyaalangal': 'Coolie company identifiers',
  'kooliNiruvanaPeyar': 'Coolie Company Name',
  'kooliTharavugal': 'Coolie Data',
  'mothaKanakku': 'Total Invoiced',
  'mothaPattiyalgal': 'Total Invoices',
  'muzhuThallupadi': 'Global Discount',
  'nirilKooli': 'Niril Coolie',
  'nirilPattu': 'Niril Silk',
  'pattiyal': 'Invoice',
  'pattiyalEn': 'Invoice Number',
  'pattiyalEnnikai': 'Invoice Count',
  'pattiyalKuriyeedu': 'Bill No.',
  'pattiyalMudhanmozhi': 'Select Primary Billing Language',
  'pattiyalThaervukkuPinVaangunarTharavugalNirappappadum': 'Customer details will be auto-filled after selecting an invoice.',
  'pattiyalTharavugal': 'Invoice Details',
  'pattiyalVagai': 'Invoice Type',
  'pattiyalaiThaernhedu': 'Select Invoice',
  'pattiyalgal': 'Invoices',
  'pattiyalgalaiThaernhedu': 'Select Invoices',
  'pattiyalgstelidhu': 'Your Billing & GST, Sorted.',
  'pattiyalmozhi': 'Which language would you like to use for your bills?',
  'pattuMugappupPakkam': 'Silk Home Page',
  'pattuNiruvanaAdaiyaalangal': 'Silk company identifiers',
  'pattuTharavugal': 'Silk Data',
  'pudhiyaPattiyal': 'New Bill',
  'thallupadi': 'Discount',
  'variArikkai': 'GST Return',
  'variArikkaigal': 'GST Returns',
  'varipPattiyal': 'Tax Invoice',

  // ── Receipts & Payments (Patrucheettu) ──
  'cheluthiyaTharavu': 'Payment Details',
  'cheluthumMuraiThaernhedu': 'Select payment mode',
  'cheluthumMuraiVinmeen': 'Payment Mode *',
  'kaasu': 'Cash',
  'kanakkuEnIfsc': 'Bank details',
  'koolipPatrucheettuThiruthi': 'Coolie Receipt Editor',
  'koolipattiyalukku': 'Used for Coolie bills and receipts.',
  'patrucheettu': 'Receipt',
  'patrucheettuChaemikkappattadhu': 'Receipt saved',
  'patrucheettuEn': 'Receipt Number',
  'patrucheettuEnYaerkanavaeUlladhu': 'Receipt number already exists!',
  'patrucheettuEnnikai': 'Receipt Count',
  'patrucheettuNaal': 'Receipt Date',
  'patrucheettuTharavugal': 'Receipt Details',
  'patrucheettuVagai': 'Receipt Type',
  'patrucheettugal': 'Receipts',
  'pattiyalPatrucheettuMozhi': 'Invoice & Receipt Language',
  'pattupPatrucheettuThiruthi': 'Silk Receipt Editor',
  'pudhiyaKoolipPatrucheettu': 'New Coolie Receipt',
  'pudhiyaPattupPatrucheettu': 'New Silk Receipt',
  'vangi': 'Bank',
  'vangiParimaatram': 'Bank Transfer',
  'vangiTharavuKaattu': 'Show Bank Details',
  'vangiyinPeyar': 'Bank Name',

  // ── Calendar & Dates ──
  'aagast': 'Aug',
  'aepral': 'Apr',
  'aktobar': 'Oct',
  'arivan': 'Wednesday',
  'chevvaay': 'Tuesday',
  'disambar': 'December',
  'janKurugiya': 'Jan',
  'fibKurugiya': 'Feb',
  'maarKurugiya': 'Mar',
  'aepKurugiya': 'Apr',
  'maeKurugiya': 'May',
  'joonKurugiya': 'Jun',
  'joolKurugiya': 'Jul',
  'aagKurugiya': 'Aug',
  'sepKurugiya': 'Sep',
  'akKurugiya': 'Oct',
  'navKurugiya': 'Nov',
  'disKurugiya': 'Dec',
  'fibravari': 'Feb',
  'janavari': 'Jan',
  'joolai': 'Jul',
  'joon': 'Jun',
  'kaari': 'Saturday',
  'maarch': 'Mar',
  'mae': 'May',
  'murpagal': 'AM',
  'naal': 'Date',
  'navambar': 'Nov',
  'nyaayiru': 'Sunday',
  'pirpagal': 'PM',
  'septambar': 'Sep',
  'thingal': 'Monday',
  'velli': 'Friday',
  'viyaazhan': 'Thursday',

  // ── Errors & Alerts ──
  'chaemikkaIyalavillai': 'Could not save:',
  'illai': 'None',
  'kaiyoppamIllai': 'No Signature',
  'kurippuEnParimaatraEn': 'Reference No / Transaction No',
  'nirandharaAzhippuUrudhi': 'Delete permanently? This cannot be undone.',
  'niruvanapeyaraiullidu': 'Please enter all required company names.',
  'oavuruIllai': 'No Logo',
  'patrucheettugalIllai': 'No Receipts',
  'pattiyalgalIllai': 'No invoices yet',
  'pizhai': 'Error',
  'ta': 'Tamil',
  'en': 'English',
};
