const Map<String, String> ta = {
  // ── Core / Common ──
  'aakku': 'ஆக்கு',
  'aangilam': 'ஆங்கிலம்',
  'adaiyaalam': 'அடையாளம்',
  'aetrugiradhu': 'ஏற்றுகிறது...',
  'agalamaanaOavuruMattum': 'அகலமான ஓவுரு மட்டும்',
  'agalamaanaoavuru': 'செங்குத்து / அகலமான ஓவுரு',
  'alaveeduMurai': 'அளவீடு முறை',
  'alavu': 'அளவு',
  'alavuVagai': 'அளவு வகை',
  'aluvalkaiyoppam': 'அலுவல் கையொப்பத்தின் பெயர்',
  'anjalKuriyeedu': 'அஞ்சல் குறியீடு',
  'appPeyar': 'Elvan Niril',
  'arikkai': 'அறிக்கை',
  'arikkaigal': 'அறிக்கைகள்',
  'arugilSeyalgal': 'நடப்பு வினைகள்',
  'attai': 'அட்டை',
  'azhikkiradhu': 'அழிக்கிறது...',
  'azhippuvetri': 'தரவு வெற்றிகரமாக அழிக்கப்பட்டது.',
  'chaedhaaram': 'சேதாரம்',
  'chaedhaaramGiraam': 'சேதாரம் (g)',
  'chaemikkaadhaVaraivu': 'சேமிக்காத வரைவு. மீட்டமைக்கவா?',
  'chaemikkappadugiradhu': 'சேமிக்கப்படுகிறது...',
  'chaemippuNiluvai': 'சேமிப்பு நிலுவை',
  'chaemippuvetri': 'வெற்றிகரமாகச் சேமிக்கப்பட்டது',
  'chaemiththaTharavugal': 'சேமித்த தரவுகள்',
  'cheyaliPatri': 'செயலி பற்றி',
  'cheyaliPatriMaadhiri': 'செயலி பற்றி (மாதிரி)',
  'cheyalipadhippu': 'செயலியின் பதிப்பு மற்றும் தரவுகள்',
  'cheyalithTharavaiAzhi': 'செயலித் தரவை அழி',
  'cheyaliyilirundhuVeliyaeravum': 'செயலியிலிருந்து வெளியேறவும்.',
  'chinnathinVadivam': 'ஓவுருவின் வடிவம்',
  'chiriyaOavuruPeyar': 'சிறிய ஓவுரு + பெயர்',
  'chuttruOppu': 'முழுமையாக்கம்',
  'edai': 'எடை',
  'elvanNiril': 'எல்வன் நிறிள்',
  'elvanParthasarathy': 'எல்வன் பார்த்தசாரதி',
  'elvanPatriMaelumAriga': 'எல்வன் பற்றி மேலும் அறிக',
  'en': 'ஆங்கிலம்',
  'endhachCheyalmurai': 'எந்தச் செயல்முறை?',
  'english': 'ஆங்கிலம்',
  'ifscKaattu': 'IFSC காட்டு',
  'ifscKuriyeedu': 'IFSC குறியீடு',
  'india': 'இந்தியா',
  'irudhiPeyar': 'இறுதிப்பெயர்',
  'irulNilai': 'இருள் நிலை',
  'kaasoalai': 'காசோலை',
  'kaiyaalu': 'கையாளு',
  'kaiyoppam': 'கையொப்பம்',
  'kanakkuEn': 'கணக்கு எண்',
  'kanakkuKuriyeedu': 'க/எ எண்',
  'kattanaPeyar': 'கட்டணப் பெயர்',
  'kilai': 'கிளை',
  'kilaipPeyar': 'கிளைப் பெயர்',
  'koriyar': 'கொரியர்',
  'koriyarKattanam': 'கொரியர் (₹)',
  'kurippu': 'குறிப்பு',
  'kurugiyaNiruvanaPeyar': 'குறுகிய நிறுவனப் பெயர்',
  'maanilam': 'மாநிலம்',
  'maanilamThaedu': 'மாநிலம் தேடுக...',
  'maanilamThaerodhu': 'மாநிலம் தேர்ந்தெடு',
  'maatru': 'மாற்று',
  'maatruPaesiEn': 'மாற்று பேசி எண்',
  'maavattam': 'மாவட்டம்',
  'meendumThaedu': 'மீண்டும் தேடு',
  'meeteduppuVetri': 'வெற்றிகரமாக மீட்கப்பட்டது',
  'meetkavum': 'மீட்கவும்',
  'meetpagam': 'மீட்பகம்',
  'meetpagam30Naal': 'மீட்பகத்தில் உள்ளவை 30 நாள்களுக்குப் பிறகு தானாகவே அழிக்கப்படும்',
  'meetpagamKaaliyanadhu': 'மீட்பகம் காலியானது',
  'meetteduppuvetri': 'தரவு வெற்றிகரமாக மீட்டெடுக்கப்பட்டது!',
  'minnanjal': 'மின்னஞ்சல்',
  'minnanjalMugavari': 'மின்னஞ்சல் முகவரி',
  'minnanjalaiUllidavum': 'மின்னஞ்சலை உள்ளிடவும்',
  'minnanjalaiUrudhiseiga': 'மின்னஞ்சலை உறுதிசெய்க',
  'mothaEdai': 'மொத்த எடை',
  'motham': 'மொத்தம்',
  'mothangal': 'மொத்தங்கள்',
  'mudhalPeyar': 'முதற்பெயர்',
  'mudindhadhu': 'முடிந்தது',
  'mugappu': 'முகப்பு',
  'mugavari': 'முகவரி',
  'mugavaritharavugal': 'நிறுவன முகவரித் தரவுகள்',
  'munthogai': 'முன்தொகை',
  'munvaraivu': 'முன்வரைவு',
  'naadu': 'நாடு',
  'niraagari': 'நிராகரி',
  'nirandharaAzhippu': 'நிரந்தரமாக அழி',
  'niril': 'நிறிள்',
  'nirilthodanga': 'நிறிளை தொடங்க கீழ் உள்ள பொத்தானை தட்டவும்',
  'niruvanam': 'நிறுவனம்',
  'niruvanathTharavu': 'நிறுவனத் தரவு',
  'niruvanangal': 'நிறுவனங்கள்',
  'niruvanathinOavuru': 'நிறுவனத்தின் ஓவுரு',
  'niruvanathinPeyar': 'நிறுவனத்தின் பெயர்',
  'niruvanaththaithThaernhedu': 'நிறுவனத்தைத் தேர்ந்தெடு',
  'oliNilai': 'ஒளி நிலை',
  'olirIrulThaaniyangu': 'ஒளி இருள் தானியங்கு',
  'oodhaa': 'ஊதா',
  'oor': 'ஊர்',
  'paadhugaappu': 'பாதுகாப்பு',
  'pachai': 'பச்சை',
  'padammoolam': 'படத்தின் மூலத்தைத் தேர்ந்தெடுக்கவும்',
  'padhivaetru': 'பதிவேற்று',
  'paesiEn': 'பேசி எண்',
  'paesiEnkal': 'பேசி எண்கள்',
  'payanar': 'பயனர்',
  'payanarVilakkam': 'இப்பெயர் முகப்புத்திரையில் தோன்றும்.',
  'payanpaduthiyaChaemippu': 'பயன்படுத்திய சேமிப்பு',
  'pazhaiyaTharavaiMeettedukkavaa': 'பழைய தரவை மீட்டெடுக்கவா?',
  'pazhaiyaTharavuKidaikkiradhu': 'பழைய தரவு கிடைக்கிறது',
  'pdfThoatram': 'PDF தோற்றம்',
  'perumMotham': 'மொத்தத் தொகை',
  'perunar': 'பெறுநர்',
  'peyarEarkanavaeUlladhu': 'இப்பெயர் ஏற்கனவே உள்ளது.',
  'peyaraiUlliduga': 'பெயரை உள்ளிடுக',
  'pira': 'பிற',
  'piraVarivuChaer': 'பிற கட்டணம் சேர்',
  'pirandhaThaedhi': 'பிறந்த தேதி',
  'pudhiyaAakkam': 'புதிய ஆக்கம்',
  'pudhiyaChaerkkai': 'புதிய சேர்க்கை',
  'pugaippadakKaruvi': 'புகைப்படக் கருவி',
  'pugaippadathThoguppu': 'புகைப்படத் தொகுப்பு',
  'ta': 'தமிழ்',
  'tamil': 'தமிழ்',
  'tamilLatin': 'தமிழ் இலத்தீன்',
  'thaaniyangki': 'தானியங்கி',
  'thaaniyangkiUruvaam': 'சேமிக்கையில் தானே உருவாகும்',
  'thaeduga': 'தேடுக...',
  'thaerndhedu': 'தேர்ந்தெடு',
  'thallupadiChurukkam': 'த.படி',
  'thamizh': 'தமிழ்',
  'thamizhAangilamThaaniyangu': 'தமிழ், ஆங்கிலம், தானியங்கு',
  'tharavaiMeettedukkiradhu': 'தரவை மீட்டெடுக்கிறது...',
  'tharavaiazhi': 'தரவுகளை முற்றிலும் அழிக்கவும்.',
  'tharavugalChaemippuVetri': 'தரவுகள் வெற்றிகரமாக சேமிக்கப்பட்டன',
  'tharavugalaiUlliduga': 'தரவுகளை உள்ளிடுக',
  'tharavugalaiUruvaakkuUruvaakkunar': 'தரவுகளை உருவாக்கு (உருவாக்குனர்)',
  'tharpoadhaiyaNiruvanam': 'தற்போதைய நிறுவனம்',
  'thirai': 'திரை',
  'thodarpuVari': 'தொடர்பு & வரி',
  'thogaiChuzhiyaththaiVidaMigudhiyaagaIrukkaVaendum': 'தொகை 0-ஐ விட மிகுதியாக இருக்க வேண்டும்',
  'thogaiVinmeen': 'தொகை *',
  'tholaipaesi': 'தொலைப்பேசி',
  'ulmotham': 'இடைமொத்தம்',
  'ungalCheyalmuraiyaithThaerndhedukkavum': 'உங்கள் செயல்முறையைத் தேர்ந்தெடுக்கவும்',
  'uruvaakkunarTharavugalaiAzhi': 'உருவாக்குனர்: தரவுகளை அழி',
  'uruvaakkunarTharavugalaiUruvaakku': 'உருவாக்குனர்: தரவுகளை உருவாக்கு',
  'vaangunarPeyarThaedu': 'வாங்குநர் பெயர்',
  'vaangunarTharavugal': 'வாங்குநர் தரவுகள்',
  'vanakkam': 'வணக்கம்!',
  'varaivu': 'வரைவு',
  'varaivuMeetka': 'வரைவு மீட்கவா?',
  'variThirattiyavai': 'வரி திரட்டியவை',
  'vazhangalIdam': 'வழங்கல் இடம்',
  'velinaadMugavari': 'முழு முகவரி',
  'veliyaeraVaendumaa': 'வெளியேற வேண்டுமா?',
  'veliyaeru': 'வெளியேறு',
  'veliyaerugiradhu': 'வெளியேறுகிறது...',
  'veliyaetramvetri': 'வெற்றிகரமாக வெளியேற்றப்பட்டது',
  'vidupattaPulangalaiNirappavum': 'விடுபட்ட புலங்களை நிரப்பவும்.',
  'vilai': 'விற்பனை விலை',
  'vilaiMatrumVari': 'விலை மற்றும் வரி',
  'vilaiVeedham': 'விலை',

  // ── Authentication & Onboarding ──
  'cheyaliyaiAnugaUlnuzhaiyavum': 'செயலியை அணுக உள்நுழையவும்',
  'kadavuchol': 'கடவுச்சொல்',
  'kadavuchollaiUllidavum': 'கடவுச்சொல்லை உள்ளிடவும்',
  'nirilirkuNalvaravu': 'நிறிளிற்கு நல்வரவு',
  'niruvanaThannuru': 'நிறுவனத் தன்னுரு',
  'niruvanamThaerodhu': 'நிறுவனத்தைத் தேர்ந்தெடு',
  'perumalavu5thannuru': 'பெருமளவு 5 தன்னுருக்கள் மட்டுமே',
  'pudhiyaThannuruChaer': 'புதிய தன்னுரு சேர்',
  'pudhiyaThannuruvaiUruvaakku': 'புதிய தன்னுருவை உருவாக்கு',
  'thannuruChaemikkappattadhu': 'தன்னுரு சேமிக்கப்பட்டது!',
  'thannuruNeekkappattadhu': 'தன்னுரு நீக்கப்பட்டது',
  'thannurukkalIllai': 'தன்னுருக்கள் இல்லை',
  'thannuruvaiMutrilumNeekkavaa': 'தன்னுருவை முற்றிலும் நீக்கவா?',
  'ulnuzhaiga': 'உள்நுழைக',

  // ── Navigation & Actions (Buttons) ──
  'anaithaiyumTheriPtn': 'அனைத்தையும் தேர்',
  'anaiththaiyumPaarPtn': 'யாவும்',
  'azhikka': 'அழிக்க',
  'chaemiPtn': 'சேமி',
  'chaer': 'சேர்',
  'chaerPtn': 'சேர்',
  'chariPtn': 'சரி',
  'kaappuCheiPtn': 'காப்பு செய்',
  'kaividuPtn': 'கைவிடு',
  'maatriyamai': 'மாற்றியமை',
  'meeteduppuCheiPtn': 'மீட்டெடு',
  'meetteduPtn': 'மீட்டெடு',
  'neekkuPtn': 'நீக்கு',
  'orunginaiCheyaliPtn': 'செயலியை ஒருங்கிணை',
  'payanarTharavugalaiMaetriduPtn': 'சேமி',
  'porulaichChaerPtn': 'பொருளைச் சேர்',
  'pudhiyaPatrucheettuPtn': 'புதிய பற்றுச்சீட்டு',
  'pudhiyaPattiyalPtn': 'புதிய பட்டியல்',
  'pudhiyadhaagaThodanguPtn': 'புதியதாக தொடங்கு',
  'purakkaniPtn': 'புறக்கணி',
  'thanipPayanPtn': 'தனிப்பயன்',
  'tharavaiAzhiPtn': 'தரவை அழி',
  'thodangugaPtn': 'தொடங்குக',
  'thodarPtn': 'தொடர்',
  'thodaravum': 'தொடரவும்',
  'uruvaakkuPtn': 'உருவாக்கு',
  'veliyaeruPtn': 'வெளியேறு',

  // ── Settings & Backup ──
  'adaimozhi': 'அடைமொழி',
  'amaippugal': 'அமைப்புகள்',
  'chaemippu': 'சேமிப்பு',
  'chaemippuMatrumKaappu': 'சேமிப்பு & காப்பு',
  'cheyaliAmaippugal': 'செயலி அமைப்புகள்',
  'cheyaliMozhi': 'செயலி மொழி',
  'idhuvuraiKaappuIllai': 'இதுவரை காப்பு இல்லை',
  'irandaamMozhi': 'இரண்டாம் மொழி',
  'irumozhiMurai': 'இருமொழி முறை',
  'kaappu': 'காப்பு',
  'kaapputhTharavuIllai': 'காப்புத் தரவு இல்லை, புதிதாக தொடங்குகிறது.',
  'kaapputhTharavuKidaithadhu': 'காப்புத் தரவு கிடைத்தது!',
  'kaapputhTharavuThaedal': 'காப்புத் தரவு தேடப்படுகிறது...',
  'kadaisiThaaniyakkaKaappu': 'கடைசி தானியக்கக் காப்பு',
  'language': 'மொழி',
  'mozhiThaervu': 'மொழியைத் தேர்ந்தெடு',
  'mudhanmaiMozhi': 'முதன்மை மொழி',
  'niruvanaAmaippugal': 'நிறுவன அமைப்புகள்',
  'orunginaiCheyaliVilakkam': 'அண்மை மாற்றங்களை ஒத்திசைக்கவும்.',
  'orunginaikkappattadhu': 'ஒருங்கிணைக்கப்பட்டது!',
  'orunginaikkiRadhu': 'ஒருங்கிணைக்கிறது...',
  'payanarAmaippugal': 'பயனர் அமைப்புகள்',
  'pilVadivamaippuViruppangal': 'PDF வடிவமைப்பு விருப்பங்கள்',
  'thaaniyangiAmaippu': 'தானியங்கி அமைப்பு',
  'thaekkagathaiazhi': 'ஒருகிணை, வெளியேறு, தரவு அழி',
  'tharavuKaappu': 'தரவு காப்பு',
  'tharavuKaappuChei': 'தரவு காப்பு செய்',
  'tharavuchaemippuvetri': 'தரவு ஆவணங்களில் சேமிக்கப்பட்டது.',
  'tharavuthalam': 'தரவுத்தளம்',
  'tharavuthalangalKaappaikKaiyaalu': 'தரவுத்தளங்கள் & காப்பைக் கையாளு',
  'ungalTharavaiChaemikkavum': 'உங்கள் தரவை சேமிக்கவும்.',
  'viruppaMozhiThaervu': 'விருப்பமான மொழியைத் தேர்வு செய்க',

  // ── Entities (Customer, Product) ──
  'azhikkappattaPorulgal': 'அழிக்கப்பட்ட பொருள்கள்',
  'azhikkappattaVaangunargal': 'அழிக்கப்பட்ட வாங்குநர்கள்',
  'hsnSacKuriyeedu': 'HSN/SAC குறியீடு',
  'kuriaindhOruPorul': 'குறைந்தது ஒரு பொருள் சேர்',
  'menporulVadivaalar': 'மென்பொருள் வடிவாளர்',
  'menporulVadivaalarPatri': 'மென்பொருள் வடிவாளர் பற்றி',
  'menporulVadivaalarPatriMaadhiri': 'மென்பொருள் வடிவாளர் பற்றி (மாதிரி)',
  'pattiyalEnVaangunar': 'பட்டியல் எண் / வாங்குநர்...',
  'porul': 'பொருள்',
  'porulAzhikkappattadhu': 'பொருள் அழிக்கப்பட்டது',
  'porulChaemikkappattadhu': 'பொருள் சேமிக்கப்பட்டது',
  'porulPeyarThaevai': 'பொருள் பெயர் தேவை',
  'porulTharavugal': 'பொருள் தரவுகள்',
  'porulaiChaerkkavum': 'முதல் பொருளைச் சேர்க்கவும்',
  'porulgalIllai': 'பொருட்கள் இல்லை',
  'porutkal': 'பொருட்கள்',
  'vaangunar': 'வாங்குநர்',
  'vaangunarAzhikkappattadhu': 'வாங்குநர் அழிக்கப்பட்டது',
  'vaangunarChaemikkappattadhu': 'வாங்குநர் சேமிக்கப்பட்டது',
  'vaangunarPeyar': 'வாங்குநர் பெயர்',
  'vaangunarPeyarThaevai': 'வாங்குநர் பெயர் தேவை',
  'vaangunaraiChaerkkavum': 'முதல் வணிகரைச் சேர்க்கவும்',
  'vaangunaraiThaerodhu': 'வணிகரைத் தேர்ந்தெடு',
  'vaangunaraichChaer': 'வணிகரைச் சேர்',
  'vaangunargal': 'வாங்குநர்கள்',
  'vaangunargalIllai': 'வாங்குநர்கள் இல்லை',

  // ── Invoicing & Billing (Pattiyal) ──
  'ahimsaiPattu': 'அகிம்சைப் பட்டு',
  'ahimsaiPattuThogai': 'அகிம்சைப் பட்டு (₹)',
  'endhapPattiyalukku': 'எந்தப் பட்டியலுக்கு',
  'gstVeedham': 'GST வீதம் %',
  'gstin': 'GSTIN',
  'gstinTavaru': 'GSTIN வடிவம் தவறானது',
  'gstinVariAdaiyaalaEn': 'GSTIN / வரி அடையாள எண்',
  'gstpattiyalukku': 'வழக்கமான GST பட்டியல்களுக்குப் பயன்படுத்தப்படும்.',
  'gstpirippugal': 'GST பிரிப்புகளைக் காட்டு',
  'kooliMugappupPakkam': 'கூலி முகப்புப் பக்கம்',
  'kooliNiruvanaAdaiyaalangal': 'கூலி நிறுவன அடையாளங்கள்',
  'kooliNiruvanaPeyar': 'கூலி நிறுவனப் பெயர்',
  'kooliTharavugal': 'கூலித் தரவுகள்',
  'mothaKanakku': 'மொத்தத் தொகை',
  'mothaPattiyalgal': 'மொத்தப் பட்டியல்கள்',
  'muzhuThallupadi': 'முழுத் தள்ளுபடி',
  'nirilKooli': 'நிறிள் கூலி',
  'nirilPattu': 'நிறிள் பட்டு',
  'pattiyal': 'பட்டியல்',
  'pattiyalEn': 'பட்டியல் எண்',
  'pattiyalEnnikai': 'பட்டியல் எண்ணிக்கை',
  'pattiyalKuriyeedu': 'பட்டியல் எண்',
  'pattiyalMudhanmozhi': 'பட்டியல் முதன்மொழி',
  'pattiyalThaervukkuPinVaangunarTharavugalNirappappadum': 'பட்டியலைத் தேர்ந்தெடுத்ததும் வாங்குநர் தரவுகள் தானே நிரப்பப்படும்.',
  'pattiyalTharavugal': 'பட்டியல் தரவுகள்',
  'pattiyalVagai': 'பட்டியல் வகை',
  'pattiyalaiThaernhedu': 'பட்டியலைத் தேர்ந்தெடு',
  'pattiyalgal': 'பட்டியல்கள்',
  'pattiyalgalaiThaernhedu': 'பட்டியல்களைத் தேர்ந்தெடு',
  'pattiyalgstelidhu': 'உங்கள் பட்டியல்கள் & GST, எளிதாக்கப்பட்டது.',
  'pattiyalmozhi': 'பட்டியலில் எம்மொழியை பயன்படுத்த வேண்டும்?',
  'pattuMugappupPakkam': 'பட்டு முகப்புப் பக்கம்',
  'pattuNiruvanaAdaiyaalangal': 'பட்டு நிறுவன அடையாளங்கள்',
  'pattuTharavugal': 'பட்டுத் தரவுகள்',
  'pudhiyaPattiyal': 'புதிய பட்டியல்',
  'thallupadi': 'தள்ளுபடி',
  'variArikkai': 'வரி அறிக்கை',
  'variArikkaigal': 'வரி அறிக்கைகள்',
  'varipPattiyal': 'வரிப் பட்டியல்',

  // ── Receipts & Payments (Patrucheettu) ──
  'cheluthiyaTharavu': 'கட்டணத் தரவு',
  'cheluthumMuraiThaernhedu': 'கட்டண முறையைத் தேர்ந்தெடு',
  'cheluthumMuraiVinmeen': 'கட்டண முறை *',
  'kaasu': 'காசு',
  'kanakkuEnIfsc': 'வங்கித் தரவுகள்',
  'koolipPatrucheettuThiruthi': 'கூலிப் பற்றுச்சீட்டு திருத்தி',
  'koolipattiyalukku': 'கூலி பட்டியல்கள் மற்றும் பற்றுச்சீட்டுகளுக்குப் பயன்படுத்தப்படும்.',
  'patrucheettu': 'பற்றுச்சீட்டு',
  'patrucheettuChaemikkappattadhu': 'பற்றுச்சீட்டு சேமிக்கப்பட்டது',
  'patrucheettuEn': 'பற்றுச்சீட்டு எண்',
  'patrucheettuEnYaerkanavaeUlladhu': 'பற்றுச்சீட்டு எண் ஏற்கனவே உள்ளது!',
  'patrucheettuEnnikai': 'பற்றுச்சீட்டு எண்ணிக்கை',
  'patrucheettuNaal': 'பற்றுச்சீட்டு நாள்',
  'patrucheettuTharavugal': 'பற்றுச்சீட்டு தரவுகள்',
  'patrucheettuVagai': 'பற்றுச்சீட்டு வகை',
  'patrucheettugal': 'பற்றுச்சீட்டுகள்',
  'pattiyalPatrucheettuMozhi': 'பட்டியல் & பற்றுச்சீட்டு மொழி',
  'pattupPatrucheettuThiruthi': 'பட்டுப் பற்றுச்சீட்டு திருத்தி',
  'pudhiyaKoolipPatrucheettu': 'புதிய கூலிப் பற்றுச்சீட்டு',
  'pudhiyaPattupPatrucheettu': 'புதிய பட்டுப் பற்றுச்சீட்டு',
  'vangi': 'வங்கி',
  'vangiParimaatram': 'வங்கிப் பரிமாற்றம்',
  'vangiTharavuKaattu': 'வங்கித் தரவு காட்டு',
  'vangiyinPeyar': 'வங்கியின் பெயர்',

  // ── Calendar & Dates ──
  'aagast': 'ஆகஸ்ட்',
  'aepral': 'ஏப்ரல்',
  'aktobar': 'அக்டோபர்',
  'arivan': 'அறிவன்',
  'chevvaay': 'செவ்வாய்',
  'disambar': 'டிசம்பர்',
  'janKurugiya': 'ஜன',
  'fibKurugiya': 'ஃபிப்',
  'maarKurugiya': 'மார்',
  'aepKurugiya': 'ஏப்',
  'maeKurugiya': 'மே',
  'joonKurugiya': 'ஜூன்',
  'joolKurugiya': 'ஜூலை',
  'aagKurugiya': 'ஆக',
  'sepKurugiya': 'செப்',
  'akKurugiya': 'அக்',
  'navKurugiya': 'நவ',
  'disKurugiya': 'டிச',
  'fibravari': 'ஃபிப்ரவரி',
  'janavari': 'ஜனவரி',
  'joolai': 'ஜூலை',
  'joon': 'ஜூன்',
  'kaari': 'காரி',
  'maarch': 'மார்ச்',
  'mae': 'மே',
  'murpagal': 'முற்பகல்',
  'naal': 'நாள்',
  'navambar': 'நவம்பர்',
  'nyaayiru': 'ஞாயிறு',
  'pirpagal': 'பிற்பகல்',
  'septambar': 'செப்டம்பர்',
  'thingal': 'திங்கள்',
  'velli': 'வெள்ளி',
  'viyaazhan': 'வியாழன்',

  // ── Errors & Alerts ──
  'chaemikkaIyalavillai': 'சேமிக்க இயலவில்லை:',
  'illai': 'இல்லை',
  'kaiyoppamIllai': 'கையொப்பம் இல்லை',
  'kurippuEnParimaatraEn': 'குறிப்பு எண் / பரிமாற்ற எண்',
  'nirandharaAzhippuUrudhi': 'நிரந்தரமாக அழிக்கவா? மீட்க இயலாது.',
  'niruvanapeyaraiullidu': 'தேவையான அனைத்து நிறுவனப் பெயர்களையும் உள்ளிடுக.',
  'oavuruIllai': 'ஓவுரு இல்லை',
  'patrucheettugalIllai': 'பற்றுச்சீட்டுகள் இல்லை',
  'pattiyalgalIllai': 'பட்டியல்கள் இல்லை',
  'pizhai': 'பிழை',
};
