const Map<String, String> taLatn = {
  // ── Core / Common ──
  'aakku': 'Aakku',
  'aangilam': 'Aangilam',
  'adaiyaalam': 'Adaiyaalam',
  'aetrugiradhu': 'Aetrugiradhu...',
  'agalamaanaOavuruMattum': 'Agalamaana Oavuru Mattum',
  'agalamaanaoavuru': 'Chenguthu / Agalamaana Oavuru',
  'alaveeduMurai': 'Alaveedu Murai',
  'alavu': 'Alavu',
  'alavuVagai': 'Alavu Vagai',
  'aluvalkaiyoppam': 'Aluval Kaiyoppathin Peyar',
  'anjalKuriyeedu': 'Anjal Kuriyeedu',
  'appPeyar': 'Elvan Niril',
  'arikkai': 'Arikkai',
  'arikkaigal': 'Arikkaigal',
  'arugilSeyalgal': 'Nadappu Vinaigal',
  'attai': 'Attai',
  'azhikkiradhu': 'Azhikkiradhu...',
  'azhippuvetri': 'Tharavu Vetrigaramaaga Azhikkappattadhu.',
  'chaedhaaram': 'Chaedhaaram',
  'chaedhaaramGiraam': 'Chaedhaaram (g)',
  'chaemikkaadhaVaraivu': 'Chaemikkaadha varaivu. Meettamaikkavaa?',
  'chaemikkappadugiradhu': 'Chaemikkappadugiradhu...',
  'chaemippuNiluvai': 'Chaemippu Niluvai',
  'chaemippuvetri': 'Vetrigaramaagach Chaemikkappattadhu',
  'chaemiththaTharavugal': 'Chaemitha Tharavugal',
  'cheyaliPatri': 'Cheyali Patri',
  'cheyaliPatriMaadhiri': 'Cheyali Patri (Maadhiri)',
  'cheyalipadhippu': 'Cheyaliyin Padhippu matrum Tharavugal',
  'cheyalithTharavaiAzhi': 'Cheyalith Tharavai Azhi',
  'cheyaliyilirundhuVeliyaeravum': 'Cheyaliyilirundhu Veliyaeravum.',
  'chinnathinVadivam': 'Oavuruvin Vadivam',
  'chiriyaOavuruPeyar': 'Chiriya Oavuru + Peyar',
  'chuttruOppu': 'Muzhumaiyaakkam',
  'edai': 'Edai',
  'elvanNiril': 'Elvan Niril',
  'elvanParthasarathy': 'Elvan Parthasarathy',
  'elvanPatriMaelumAriga': 'Elvan Patri Maelum Ariga',
  'en': 'Aangilam',
  'endhachCheyalmurai': 'Endhach Cheyalmurai?',
  'english': 'Aangilam',
  'ifscKaattu': 'IFSC Kaattu',
  'ifscKuriyeedu': 'IFSC Kuriyeedu',
  'india': 'Indhiya',
  'irudhiPeyar': 'Irudhi Peyar',
  'irulNilai': 'Irul Nilai',
  'kaasoalai': 'Kaasoalai',
  'kaiyaalu': 'Kaiyaalu',
  'kaiyoppam': 'Kaiyoppam',
  'kanakkuEn': 'Kanakku En',
  'kanakkuKuriyeedu': 'Ka/E En',
  'kattanaPeyar': 'Kattana Peyar',
  'kilai': 'Kilai',
  'kilaipPeyar': 'Kilaip Peyar',
  'koriyar': 'Koriyar',
  'koriyarKattanam': 'Koriyar (₹)',
  'kurippu': 'Kurippu',
  'kurugiyaNiruvanaPeyar': 'Kurugiya Niruvanap Peyar',
  'maanilam': 'Maanilam',
  'maanilamThaedu': 'Maanilam Thaeduga...',
  'maanilamThaerodhu': 'Maanilam Thaerndhedu',
  'maatru': 'Maatru',
  'maatruPaesiEn': 'Maatru Paesi En',
  'maavattam': 'Maavattam',
  'meendumThaedu': 'Meendum Thaedu',
  'meeteduppuVetri': 'Vetrigaramaaga Meetkappattadhu',
  'meetkavum': 'Meetkavum',
  'meetpagam': 'Meetpagam',
  'meetpagam30Naal': 'Meetpagatthil Ullavai 30 Naalgalukku Piragu Thaanaagavae Azhikkapppadum',
  'meetpagamKaaliyanadhu': 'Meetpagam Kaaliyanadhu',
  'meetteduppuvetri': 'Tharavu Vetrigaramaaga Meettedukkappattadhu!',
  'minnanjal': 'Minnanjal',
  'minnanjalMugavari': 'Minnanjal Mugavari',
  'minnanjalaiUllidavum': 'Minnanjalai Ullidavum',
  'minnanjalaiUrudhiseiga': 'Minnanjalai Urudhiseiga',
  'mothaEdai': 'Motha Edai',
  'motham': 'Motham',
  'mothangal': 'Mothangal',
  'mudhalPeyar': 'Mudhal Peyar',
  'mudindhadhu': 'Mudindhadhu',
  'mugappu': 'Mugappu',
  'mugavari': 'Mugavari',
  'mugavaritharavugal': 'Niruvana Mugavarith Tharavugal',
  'munthogai': 'Munthogai',
  'munvaraivu': 'Munvaraivu',
  'naadu': 'Naadu',
  'niraagari': 'Niraagari',
  'nirandharaAzhippu': 'Nirandharamaaga Azhi',
  'niril': 'Niril',
  'nirilthodanga': 'Nirilai Thodanga Keezh Ulla Pothaanai Thattavum',
  'niruvanam': 'Niruvanam',
  'niruvanathTharavu': 'Niruvanath Tharavu',
  'niruvanangal': 'Niruvanangal',
  'niruvanathinOavuru': 'Niruvanathin Oavuru',
  'niruvanathinPeyar': 'Niruvanathin Peyar',
  'niruvanaththaithThaernhedu': 'Niruvanaththaith Thaernhedu',
  'oliNilai': 'Oli Nilai',
  'olirIrulThaaniyangu': 'Oli irul Thaaniyangu',
  'oodhaa': 'Oodhaa',
  'oor': 'Oor',
  'paadhugaappu': 'Paadhugaappu',
  'pachai': 'Pachai',
  'padammoolam': 'Padathin Moolathaith Thaerndhedukkavum',
  'padhivaetru': 'Padhivaetru',
  'paesiEn': 'Paesi En',
  'paesiEnkal': 'Paesi Enkal',
  'payanar': 'Payanar',
  'payanarVilakkam': 'Ippeyar Mugappu Thiraiyil Thoandrum.',
  'payanpaduthiyaChaemippu': 'Payanpaduthiya Chaemippu',
  'pazhaiyaTharavaiMeettedukkavaa': 'Pazhaiya Tharavai Meettedukkavaa?',
  'pazhaiyaTharavuKidaikkiradhu': 'Pazhaiya Tharavu Kidaikkiradhu',
  'pdfThoatram': 'PDF Thoatram',
  'perumMotham': 'Mothath Thogai',
  'perunar': 'Perunar',
  'peyarEarkanavaeUlladhu': 'ippeyar aerkkanavae ulladhu.',
  'peyaraiUlliduga': 'Peyarai Ulliduga',
  'pira': 'Pira',
  'piraVarivuChaer': 'Pira Kattanam Chaer',
  'pirandhaThaedhi': 'Pirandha Naal',
  'pudhiyaAakkam': 'Pudhiya Aakkam',
  'pudhiyaChaerkkai': 'Pudhiya Chaerkkai',
  'pugaippadakKaruvi': 'Pugaippadak Karuvi',
  'pugaippadathThoguppu': 'Pugaippadath Thoguppu',
  'ta': 'Thamizh',
  'tamil': 'Thamizh',
  'tamilLatin': 'Thamizh Latin',
  'thaaniyangki': 'Thaaniyangki',
  'thaaniyangkiUruvaam': 'Thaaniyangki Uruvaam',
  'thaeduga': 'Thaeduga...',
  'thaerndhedu': 'Thaerndhedu',
  'thallupadiChurukkam': 'Tha.Padi',
  'thamizh': 'Thamizh',
  'thamizhAangilamThaaniyangu': 'Thamizh, Aangilam, Thaaniyangu',
  'tharavaiMeettedukkiradhu': 'Tharavai Meettedukkiradhu...',
  'tharavaiazhi': 'Tharavugalai Mutrilum Azhikkavum.',
  'tharavugalChaemippuVetri': 'Tharavugal Vetrigaramaaga Chaemikkappattana',
  'tharavugalaiUlliduga': 'Tharavugalai Ulliduga',
  'tharavugalaiUruvaakkuUruvaakkunar': 'Tharavugalai Uruvaakku (Uruvaakkunar)',
  'tharpoadhaiyaNiruvanam': 'Tharpoadhaiya Niruvanam',
  'thirai': 'Thirai',
  'thodarpuVari': 'Thodarbu & Vari',
  'thogaiChuzhiyaththaiVidaMigudhiyaagaIrukkaVaendum': 'Thogai 0-ai vida migudhiyaaga irukka vaendum',
  'thogaiVinmeen': 'Thogai *',
  'tholaipaesi': 'Tholaippaesi',
  'ulmotham': 'Idaimotham',
  'ungalCheyalmuraiyaithThaerndhedukkavum': 'Ungal Cheyalmuraiyaith Thaerndhedukkavum',
  'uruvaakkunarTharavugalaiAzhi': 'Uruvaakkunar: Tharavugalai Azhi',
  'uruvaakkunarTharavugalaiUruvaakku': 'Uruvaakkunar: Tharavugalai Uruvaakku',
  'vaangunarPeyarThaedu': 'Vaangunar Peyar',
  'vaangunarTharavugal': 'Vanigath Tharavugal',
  'vanakkam': 'Vanakkam!',
  'varaivu': 'Varaivu',
  'varaivuMeetka': 'Varaivu Meetkavaa?',
  'variThirattiyavai': 'Vari Thirattiyavai',
  'vazhangalIdam': 'Vazhangal Idam',
  'velinaadMugavari': 'Muzhu Mugavari',
  'veliyaeraVaendumaa': 'Veliyaera Vaendumaa?',
  'veliyaeru': 'Veliyaeru',
  'veliyaerugiradhu': 'Veliyaerugiradhu...',
  'veliyaetramvetri': 'Vetrigaramaaga Veliyaetrappattadhu',
  'vidupattaPulangalaiNirappavum': 'Vidupatta pulangalai nirappavum.',
  'vilai': 'Vilai',
  'vilaiMatrumVari': 'Vilai matrum Vari',
  'vilaiVeedham': 'Vilai',

  // ── Authentication & Onboarding ──
  'cheyaliyaiAnugaUlnuzhaiyavum': 'Cheyaliyai Anuga Ulnuzhaiyavum',
  'kadavuchol': 'Kadavuchol',
  'kadavuchollaiUllidavum': 'Kadavuchollai Ullidavum',
  'nirilirkuNalvaravu': 'Nirilirku Nalvaravu',
  'niruvanaThannuru': 'Niruvana Thannuru',
  'niruvanamThaerodhu': 'Niruvanatthai Thaerndhedu',
  'perumalavu5thannuru': 'Perumalavu 5 Thannurukkal Mattumae',
  'pudhiyaThannuruChaer': 'Pudhiya Thannuru Chaer',
  'pudhiyaThannuruvaiUruvaakku': 'Pudhiya Thannuruvai Uruvaakku',
  'thannuruChaemikkappattadhu': 'Thannuru Chaemikkappattadhu!',
  'thannuruNeekkappattadhu': 'Thannuru Neekkappattadhu',
  'thannurukkalIllai': 'Thannurukkal Illai',
  'thannuruvaiMutrilumNeekkavaa': 'Thannuruvai Mutrilum Neekkavaa?',
  'ulnuzhaiga': 'Ulnuzhaiga',

  // ── Navigation & Actions (Buttons) ──
  'anaithaiyumTheriPtn': 'Anaithaiyum Theri',
  'anaiththaiyumPaarPtn': 'Yaavum',
  'azhikka': 'Azhikka',
  'chaemiPtn': 'Chaemi',
  'chaer': 'Chaer',
  'chaerPtn': 'Chaer',
  'chariPtn': 'Chari',
  'kaappuCheiPtn': 'Kaappu Chei',
  'kaividuPtn': 'Kaividu',
  'maatriyamai': 'Maatriyamai',
  'meeteduppuCheiPtn': 'Meetteduppu Chei',
  'meetteduPtn': 'Meettedu',
  'neekkuPtn': 'Neekku',
  'orunginaiCheyaliPtn': 'Cheyaliyai Orunginai',
  'payanarTharavugalaiMaetriduPtn': 'Chaemi',
  'porulaichChaerPtn': 'Porulaich Chaer',
  'pudhiyaPatrucheettuPtn': 'Pudhiya Patrucheettu',
  'pudhiyaPattiyalPtn': 'Pudhiya Pattiyal',
  'pudhiyadhaagaThodanguPtn': 'Pudhiyadhaaga Thodangu',
  'purakkaniPtn': 'Purakkani',
  'thanipPayanPtn': 'Thanippayan',
  'tharavaiAzhiPtn': 'Tharavai Azhi',
  'thodangugaPtn': 'Thodanguga',
  'thodarPtn': 'Thodar',
  'thodaravum': 'Thodaravum',
  'uruvaakkuPtn': 'Uruvaakku',
  'veliyaeruPtn': 'Veliyaeru',

  // ── Settings & Backup ──
  'adaimozhi': 'Adaimozhi',
  'amaippugal': 'Amaippugal',
  'chaemippu': 'Chaemippu',
  'chaemippuMatrumKaappu': 'Chaemippu & Kaappu',
  'cheyaliAmaippugal': 'Cheyali Amaippugal',
  'cheyaliMozhi': 'Cheyali Mozhi',
  'idhuvuraiKaappuIllai': 'Idhuvarai Kaappu Illai',
  'irandaamMozhi': 'Irandaam Mozhi',
  'irumozhiMurai': 'Irumozhi Murai',
  'kaappu': 'Kaappu',
  'kaapputhTharavuIllai': 'Kaapputh Tharavu Illai, Pudhidhaaga Thodangugiradhu.',
  'kaapputhTharavuKidaithadhu': 'Kaapputh Tharavu Kidaithadhu!',
  'kaapputhTharavuThaedal': 'Kaapputh Tharavu Thaedappadugiradhu...',
  'kadaisiThaaniyakkaKaappu': 'Kadaisi Thaaniyakka Kaappu',
  'language': 'Mozhi',
  'mozhiThaervu': 'Mozhiyaith Thaerndhedu',
  'mudhanmaiMozhi': 'Mudhanmai Mozhi',
  'niruvanaAmaippugal': 'Niruvana Amaippugal',
  'orunginaiCheyaliVilakkam': 'Anmai maatrangalai othisaikkavum.',
  'orunginaikkappattadhu': 'Orunginaikkappattadhu!',
  'orunginaikkiRadhu': 'Orunginaikkiradhu...',
  'payanarAmaippugal': 'Payanar Amaippugal',
  'pilVadivamaippuViruppangal': 'PDF Vadivamaippu Viruppangal',
  'thaaniyangiAmaippu': 'Thaaniyangi Amaippu',
  'thaekkagathaiazhi': 'Orunginai, Veliyaeru, Tharavu Azhi',
  'tharavuKaappu': 'Tharavu Kaappu',
  'tharavuKaappuChei': 'Tharavu Kaappu Chei',
  'tharavuchaemippuvetri': 'Tharavu Aavanangalil Chaemikkappattadhu.',
  'tharavuthalam': 'Tharavuthalam',
  'tharavuthalangalKaappaikKaiyaalu': 'Tharavuthalangal & Kaappaik Kaiyaalu',
  'ungalTharavaiChaemikkavum': 'Ungal Tharavai Chaemikkavum.',
  'viruppaMozhiThaervu': 'Viruppamaana Mozhiyaith Thaervu Cheiga',

  // ── Entities (Customer, Product) ──
  'azhikkappattaPorulgal': 'Azhikkappatta Porulgal',
  'azhikkappattaVaangunargal': 'Azhikkappatta Vaangunargal',
  'hsnSacKuriyeedu': 'HSN/SAC Kuriyeedu',
  'kuriaindhOruPorul': 'Kuraindhadhu Oru Porul Chaer',
  'menporulVadivaalar': 'Menporul Vadivaalar',
  'menporulVadivaalarPatri': 'Menporul Vadivaalar Patri',
  'menporulVadivaalarPatriMaadhiri': 'Menporul Vadivaalar Patri (Maadhiri)',
  'pattiyalEnVaangunar': 'Pattiyal en / Vaangunar...',
  'porul': 'Porul',
  'porulAzhikkappattadhu': 'Porul Azhikkappattadhu',
  'porulChaemikkappattadhu': 'Porul Chaemikkappattadhu',
  'porulPeyarThaevai': 'Porul Peyar Thaevai',
  'porulTharavugal': 'Porul Tharavugal',
  'porulaiChaerkkavum': 'Mudhal Porulai Chaerkkavum',
  'porulgalIllai': 'Porutkal Illai',
  'porutkal': 'Porutkal',
  'vaangunar': 'Vaangunar',
  'vaangunarAzhikkappattadhu': 'Vaangunar Azhikkappattadhu',
  'vaangunarChaemikkappattadhu': 'Vaangunar Chaemikkappattadhu',
  'vaangunarPeyar': 'Vaangunar Peyar',
  'vaangunarPeyarThaevai': 'Vaangunar Peyar Thaevai',
  'vaangunaraiChaerkkavum': 'Mudhal Vaangunaraich Chaerkkavum',
  'vaangunaraiThaerodhu': 'Vaangunarai Thaerndhedu',
  'vaangunaraichChaer': 'Vaangunaraich Chaer',
  'vaangunargal': 'Vaangunargal',
  'vaangunargalIllai': 'Vaangunargal Illai',

  // ── Invoicing & Billing (Pattiyal) ──
  'ahimsaiPattu': 'Ahimsai Pattu',
  'ahimsaiPattuThogai': 'Ahimsai Pattu (₹)',
  'endhapPattiyalukku': 'Endhap Pattiyalukku?',
  'gstVeedham': 'GST Veedham %',
  'gstin': 'GSTIN',
  'gstinTavaru': 'GSTIN Vadivam Thavaraanadhu',
  'gstinVariAdaiyaalaEn': 'GSTIN / Vari Adaiyaala En',
  'gstpattiyalukku': 'Vazhakkamaana GST Pattiyalgalukkup Payanbaduthappadum.',
  'gstpirippugal': 'GST Pirippugalaik Kaattu',
  'kooliMugappupPakkam': 'Kooli Mugappup Pakkam',
  'kooliNiruvanaAdaiyaalangal': 'Kooli Niruvana Adaiyaalangal',
  'kooliNiruvanaPeyar': 'Kooli Niruvanap Peyar',
  'kooliTharavugal': 'Koolith Tharavugal',
  'mothaKanakku': 'Mothath Thogai',
  'mothaPattiyalgal': 'Mothap Pattiyalgal',
  'muzhuThallupadi': 'Muzhu Thallupadi',
  'nirilKooli': 'Niril Kooli',
  'nirilPattu': 'Niril Pattu',
  'pattiyal': 'Pattiyal',
  'pattiyalEn': 'Pattiyal En',
  'pattiyalEnnikai': 'Pattiyal Ennikkai',
  'pattiyalKuriyeedu': 'Pattiyal En',
  'pattiyalMudhanmozhi': 'Pattiyal Mudhanmozhi',
  'pattiyalThaervukkuPinVaangunarTharavugalNirappappadum': 'Pattiyalait Thaerndhedutthadhum Vaangunar Tharavugal Thaanae Nirappappadum.',
  'pattiyalTharavugal': 'Pattiyal Tharavugal',
  'pattiyalVagai': 'Pattiyal Vagai',
  'pattiyalaiThaernhedu': 'Pattiyalai Thaernhedu',
  'pattiyalgal': 'Pattiyalgal',
  'pattiyalgalaiThaernhedu': 'Pattiyalgalai thaernhedu',
  'pattiyalgstelidhu': 'Ungal Pattiyalgal & GST, Elidhaakkappattadhu.',
  'pattiyalmozhi': 'Pattiyalil Emmozhiyai Payanbadutha Vaendum?',
  'pattuMugappupPakkam': 'Pattu Mugappup Pakkam',
  'pattuNiruvanaAdaiyaalangal': 'Pattu Niruvana Adaiyaalangal',
  'pattuTharavugal': 'Pattuth Tharavugal',
  'pudhiyaPattiyal': 'Pudhiya Pattiyal',
  'thallupadi': 'Thallupadi',
  'variArikkai': 'Vari Arikkai',
  'variArikkaigal': 'Vari Arikkaigal',
  'varipPattiyal': 'Varip Pattiyal',

  // ── Receipts & Payments (Patrucheettu) ──
  'cheluthiyaTharavu': 'Kattanath Tharavu',
  'cheluthumMuraiThaernhedu': 'Kattana Muraiyai Thaerndhedu',
  'cheluthumMuraiVinmeen': 'Kattana Murai *',
  'kaasu': 'Kaasu',
  'kanakkuEnIfsc': 'Vangi Tharavugal',
  'koolipPatrucheettuThiruthi': 'Koolip Patrucheettu Thiruthi',
  'koolipattiyalukku': 'Kooli Pattiyalgal Matrum Patrucheettugalukkup Payanbaduthappadum.',
  'patrucheettu': 'Patrucheettu',
  'patrucheettuChaemikkappattadhu': 'Patrucheettu chaemikkappattadhu',
  'patrucheettuEn': 'Patrucheettu En',
  'patrucheettuEnYaerkanavaeUlladhu': 'Patrucheettu en yaerkanavae ulladhu!',
  'patrucheettuEnnikai': 'Patrucheettu Ennikkai',
  'patrucheettuNaal': 'Patrucheettu Naal',
  'patrucheettuTharavugal': 'Patrucheettu Tharavugal',
  'patrucheettuVagai': 'Patrucheettu Vagai',
  'patrucheettugal': 'Patrucheettugal',
  'pattiyalPatrucheettuMozhi': 'Pattiyal & Patrucheettu Mozhi',
  'pattupPatrucheettuThiruthi': 'Pattup Patrucheettu Thiruthi',
  'pudhiyaKoolipPatrucheettu': 'Pudhiya Koolip Patrucheettu',
  'pudhiyaPattupPatrucheettu': 'Pudhiya Pattup Patrucheettu',
  'vangi': 'Vangi',
  'vangiParimaatram': 'Vangip Parimaatram',
  'vangiTharavuKaattu': 'Vangi Tharavu Kaattu',
  'vangiyinPeyar': 'Vangiyin Peyar',

  // ── Calendar & Dates ──
  'aagast': 'Aagast',
  'aepral': 'Aepral',
  'aktobar': 'Aktobar',
  'arivan': 'Arivan',
  'chevvaay': 'Chevvaay',
  'disambar': 'Disambar',
  'janKurugiya': 'Jan',
  'fibKurugiya': 'Fib',
  'maarKurugiya': 'Maar',
  'aepKurugiya': 'Aep',
  'maeKurugiya': 'Mae',
  'joonKurugiya': 'Joon',
  'joolKurugiya': 'Jool',
  'aagKurugiya': 'Aag',
  'sepKurugiya': 'Sep',
  'akKurugiya': 'Ak',
  'navKurugiya': 'Nav',
  'disKurugiya': 'Dis',
  'fibravari': 'Fibravari',
  'janavari': 'Janavari',
  'joolai': 'Joolai',
  'joon': 'Joon',
  'kaari': 'Kaari',
  'maarch': 'Maarch',
  'mae': 'Mae',
  'murpagal': 'Murpagal',
  'naal': 'Naal',
  'navambar': 'Navambar',
  'nyaayiru': 'Nyaayiru',
  'pirpagal': 'Pirpagal',
  'septambar': 'Septambar',
  'thingal': 'Thingal',
  'velli': 'Velli',
  'viyaazhan': 'Viyaazhan',

  // ── Errors & Alerts ──
  'chaemikkaIyalavillai': 'Chaemikka iyalavillai:',
  'illai': 'Illai',
  'kaiyoppamIllai': 'Kaiyoppam Illai',
  'kurippuEnParimaatraEn': 'Kurippu En / Parimaatra En',
  'nirandharaAzhippuUrudhi': 'Nirandharamaaga Azhikkavaa? Meetka Iyalaadhu.',
  'niruvanapeyaraiullidu': 'Thaevaiyaana Anaithu Niruvanap Peyargalaiyum Ullidavum.',
  'oavuruIllai': 'Oavuru Illai',
  'patrucheettugalIllai': 'Patrucheettugal illai',
  'pattiyalgalIllai': 'Pattiyalgal Illai',
  'pizhai': 'Pizhai',
};
