// @ts-nocheck
import { TranslationKey } from './ta';

export const en: Record<TranslationKey, string> = {
  // App General
  appName: 'Niril',
  appNameFull: 'Elvan Niril',
  welcomeBack: 'Welcome back!',
  loading: 'Loading...',
  error: 'Error',
  save: 'Save',
  cancel: 'Cancel',
  back: 'Back',
  edit: 'Edit',
  delete: 'Delete',
  add: 'Add',
  search: 'Search...',
  print: 'Print',
  preview: 'Preview',
  actions: 'Actions',
  done: 'Done',
  selectInvoices: 'Select Invoices',
  searchInvoices: 'Search by invoice no. or customer...',
  yes: 'Yes',
  no: 'No',
  selected: 'Selected',
  copyDuplicate: 'Copy / Duplicate',
  connected: 'Connected',
  offlineMode: 'Offline mode',
  connecting: 'Connecting...',

  // Navigation / Sidebar
  home: 'Home',
  invoices: 'Invoices',
  accountingGroup: 'Accounting',
  reportsGroup: 'Reports & GST',
  coolieBill: 'Coolie Bill',
  silksBill: 'Grocery Bill',
  newBill: 'New Bill',
  bills: 'Bills',
  allBills: 'All Bills',
  merchants: 'Merchants',
  inventory: 'Products',
  inventoryTitle: 'Products',
  inventorySubtitle: 'Manage your products and services',
  receipts: 'Receipts',
  newPaymentReceiptTitle: 'New Payment Receipt',
  editReceiptTitle: 'Edit Receipt',
  expenses: 'Expenses',
  purchases: 'Purchases',
  recurring: 'Recurring',
  reports: 'Reports',
  gstReturns: 'GST Returns',
  settings: 'Settings',
  userGuide: 'User Guide',
  notifications: 'Notifications',
  logout: 'Logout',

  // Theme & Language
  darkMode: 'Dark Mode',
  lightMode: 'Light Mode',
  language: 'Language',
  appPreferences: 'App Preferences',
  appLanguage: 'App Language',
  appLanguageAppearance: 'App language and appearance settings',
  uiLanguageTheme: 'UI language, Theme',
  languageChangedTa: 'மொழி தமிழுக்கு மாற்றப்பட்டது',
  languageChangedEn: 'Language changed to English',
  storageCloud: 'Storage & Cloud',

  systemUpdates: 'System & Updates',
  systemStorage: 'System Storage',
  appVersionsCache: 'App versions, Backup, Cache',

  // Forms & Inputs
  name: 'Name',
  mugavari: 'Address',
  oor: 'City',
  district: 'District',
  state: 'State',
  county: 'County',
  province: 'Province',
  postcode: 'Postcode',
  zipCode: 'Zip Code',
  tamil: 'Tamil',
  english: 'English',
  hindi: 'Hindi',
  telugu: 'Telugu',
  kannada: 'Kannada',
  malayalam: 'Malayalam',
  marathi: 'Marathi',
  gujarati: 'Gujarati',
  bengali: 'Bengali',
  tholaipesi: 'Phone',
  email: 'Email',
  date: 'Date',
  description: 'Description',

  // Billing / Invoice
  billNo: 'Bill No',
  invoiceDetails: 'Invoice Details',
  itemsList: 'Items',
  itemName: 'Item Name',
  weight: 'Weight',
  rate: 'Rate',
  price: 'Price',
  amount: 'Amount',
  total: 'Total',
  subTotal: 'Sub Total',
  addAnotherItem: 'Add Row',
  notes: 'Notes',
  terms: 'Terms',
  
  // Merchants
  addClient: 'Add Merchant',
  newMerchant: 'New Merchant',
  merchantName: 'Merchant Name',
  editClientTitle: 'Edit Merchant',
  addNewClientTitle: 'Add New Merchant',
  clientBusinessName: 'Merchant / Business Name',
  clientNamePlaceholder: 'e.g. Elvan Corp',
  clientNamePlaceholderEn: 'Merchant Name (in English)',
  streetAddressPlaceholder: 'Street Address',
  addressPlaceholderEn: 'Address (in English)',
  cityPlaceholderEn: 'City (in English)',
  districtPlaceholder: 'District',
  districtPlaceholderEn: 'District (in English)',
  countryPlaceholderEn: 'Country (in English)',
  city: 'City',
  cityPlaceholder: 'e.g. Chennai',
  emailPlaceholder: 'merchant@example.com',
  phoneLabel: 'Phone Number',
  phonePlaceholder: '+91 98765 43210',
  cancelModalBtn: 'Cancel',
  confirmModalBtn: 'Confirm',
  updateClientModalBtn: 'Update',
  saveClientModalBtn: 'Save',
  noMerchants: 'No merchants yet',
  deleteMerchantConfirm: 'Delete this merchant?',
  duplicateCustomersTitle: 'Duplicate Merchants?',
  duplicateCustomersMessage: 'Duplicate {count} selected merchant(s)?',
  deleteMerchantsTitle: 'Delete Merchants?',
  deleteMerchantsMessage: 'Delete {count} merchant(s)? This cannot be undone.',
  customersDuplicatedSuccess: 'Merchants duplicated successfully',

  // Items
  newItem: 'New Item',
  noItems: 'No items yet',
  deleteItemConfirm: 'Are you sure you want to delete this item?',

  // Settings
  appearance: 'Appearance',
  account: 'Account',
  profile: 'Profile',
  security: 'Security',
  dataBackup: 'Data Backup',
  cloudSync: 'Cloud Sync',
  about: 'About',
  businessProfile: 'Business Profile',
  bankDetails: 'Bank Details',
  companyName: 'Company Name',
  accountNo: 'Account No',
  ifscCode: 'IFSC Code',
  kilai: 'Branch',
  
  // Messages
  successSaved: 'Saved successfully!',
  errorSaveFailed: 'Failed to save:',
  noDataAvailable: 'No Data Available',
  // Invoice Form
  billedTo: 'Billed To',
  clientName: 'Client Name',
  billingAddress: 'Billing Address',
  country: 'Country',
  pinCode: 'PIN Code',
  maanilam: 'State',
  gstin: 'GSTIN',
  invoiceDetailsForm: 'Invoice Details',
  invoiceNumber: 'Invoice Number',
  invoiceDate: 'Invoice Date',
  dueDate: 'Due Date',
  placeOfSupply: 'Place of Supply',
  lineItems: 'Line Items',
  pricesIncludeTax: 'Prices include tax',
  hsnSac: 'HSN/SAC',
  qty: 'Qty',
  unit: 'Unit',
  discount: 'Discount',
  cess: 'Cess %',

  // Settings Page
  settingsTitle: 'Settings',
  settingsSubtitle: 'Business profile, branding, integrations & data',
  modulesTitle: 'Modules',
  modulesDesc: 'Turn off unused features. Your data remains safe.',
  regionTitle: 'Region Preference',
  regionDesc: 'Choose how the app behaves. You can change this any time without losing data.',
  companyDetailsTitle: 'Company Details',
  paymentAccountsTitle: 'Payment Accounts',
  paymentAccountsDesc: 'Add bank or UPI accounts. The default (⭐) is preselected on new invoices.',
  invoiceNumberFormatTitle: 'Invoice Number Format',
  brandingTitle: 'Branding',
  businessLogo: 'Business Logo',
  signature: 'Signature / Stamp',
  cloudBackupTitle: 'Cloud Backup (Google Drive)',
  cloudBackupDesc: 'Auto-sync your invoices to Google Drive — no coding or API setup needed.',
  exportImportTitle: 'Export & Import Data',
  exportImportDesc: 'Backup your data locally or restore from a previous backup file.',
  resetToDefault: 'Reset to default',

  // Module Groups
  moduleGroup_sales: 'Sales & Invoicing',
  moduleDesc_sales: 'Invoice creation, recurring invoices, payment receipts',
  module_invoicing: 'Tax invoices, proforma, credit notes',
  module_recurring: 'Recurring invoices',
  module_receipts: 'Payment receipts',

  moduleGroup_directory: 'Directory',
  moduleDesc_directory: 'Clients and product catalog',
  module_clients: 'Clients',
  module_inventory: 'Products & Services',

  moduleGroup_purchases: 'Purchases & Expenses',
  moduleDesc_purchases: 'Vendor bills, expense tracking, ITC',
  module_expenses: 'Expense tracker',
  module_purchases: 'Purchase bills',
  module_gstr2b: 'GSTR-2B reconciliation (purchase ITC matching)',

  moduleGroup_gst: 'GST & Tax (India)',
  moduleDesc_gst: 'GSTR returns, e-Way Bill, TDS/TCS, HSN summaries',
  module_gstReturns: 'GSTR-1 / GSTR-3B exports + filing guide',
  module_ewayBill: 'E-Way Bill JSON export',
  module_tdsTcs: 'TDS / TCS on invoices',

  moduleGroup_reports: 'Reports',
  moduleDesc_reports: 'Dashboards and financial reports',
  module_dashboard: 'Dashboard',
  module_reports: 'Reports view',

  moduleGroup_integrations: 'Integrations',
  moduleDesc_integrations: 'Cloud backup and payment QR codes',

  module_upiQr: 'UPI QR code on invoices',

  // Settings Form
  businessNameLabel: 'Business Name',
  addProductTitle: 'Add New Product',
  editProductTitle: 'Edit Product',
  productNameLabel: 'Product / Service Name',
  hsnCodeLabel: 'HSN / SAC Code',
  rateLabel: 'Rate (Base Price)',
  gstPercentLabel: 'GST %',
  productAddedToast: 'Product Added Successfully',
  productUpdatedToast: 'Product Updated',
  failedToSaveProductToast: 'Failed to Save Product',
  productNameRequiredToast: 'Product Name is Required',
  countryLabel: 'Country',
  mugavariLabel: 'Address',
  oorLabel: 'City / Town',
  emailLabel: 'Email',
  tholaipesiLabel: 'Phone',
  mobileLabel: 'Mobile',
  orgNameEn: 'Organization Name (English)',
  shortBusinessName: 'Short Business Name',
  shortBusinessNameHint: 'Used as the default prefix for your invoice numbers.',
  phoneNumbers: 'Phone Numbers',
  address: 'Address',
  contactBank: 'Contact & Bank',
  businessSettings: 'Business Settings',
  bank: 'Bank',
  branding: 'Branding',
  invoiceSettings: 'Invoice Settings',
  languageSettings: 'Language Settings',
  nirilCoolie: 'Niril Coolie',
  nirilSilk: 'Niril Silk',
  companyAddressDetails: 'Company address details',
  logoSignatures: 'Logo & Signatures',
  accountNumberIfsc: 'Account number, IFSC',
  invoiceTab: 'Invoice',
  invoiceStylingOptions: 'Invoice styling options',
  languages: 'Languages',
  dataEntryLanguages: 'Data entry languages',
  colorsTheme: 'Colors & Theme',
  createNewBusinessProfile: 'Create New Business Profile',
  businessName: 'Business Name',
  gstinOptional: 'GSTIN (Optional)',
  addressOptional: 'Address (Optional)',
  fillDetailsLater: 'You can fill in the rest of the details later from Settings.',
  creating: 'Creating...',
  createBtn: 'Create',
  unsavedChangesContinue: 'You have unsaved changes. Continue without saving?',
  profileDeleted: 'Profile deleted',
  changesDiscarded: 'Changes discarded',
  settingsSaved: 'Settings saved!',
  activeProfile: 'Active Profile',
  closeBtn: 'Close',
  manageBtn: 'Manage',
  addNewBtn: 'Add New',
  createNewProfileModalTitle: 'Create New Profile',
  businessNameStar: 'Business Name *',
  businessNameEnglish: 'Business Name (English)',
  cancelBtn: 'Cancel',
  manageBusinessProfilesModalTitle: 'Manage Business Profiles',
  noSavedProfilesYet: 'No saved profiles yet',
  currentlyEditing: 'Currently Editing',
  deleteBtn: 'Delete',
  confirmDeleteModalTitle: 'Confirm Delete',
  permanentlyDeleteProfile: 'Permanently delete this business profile?',

  'PIN Code': 'PIN Code',
  'GSTIN': 'GSTIN',
  'Select maanilam': 'Select State',
  'e.g. Mumbai': 'e.g. Mumbai',

  // Misc Settings
  includeFinancialYear: 'Include Financial Year',
  yesFinYear: 'Yes (2026-27)',

  numberPadding: 'Number Padding',
  digits3: '3 digits (001)',
  digits4: '4 digits (0001)',
  digits5: '5 digits (00001)',
  digits6: '6 digits (000001)',
  saving: 'Saving...',
  saveNumberFormat: 'Save',
  uploadLogo: 'Upload Logo',
  logoHint: 'PNG or JPG, square or wide (max 500KB)',
  uploadSignature: 'Upload Signature',
  sigHint: 'PNG, JPG (max 500KB)',
  saveProfile: 'Save',
  
  termsTemplatesTitle: 'Terms & Conditions Templates',
  newTemplate: 'New Template',
  termsTemplatesDesc: 'Create or pick reusable terms.',
  quickStartTemplate: 'QUICK START TEMPLATES',
  templateName: 'Template Name',
  templateContent: 'Content (paste your terms here)',

  saveTemplate: 'Save',
  noTemplates: 'No templates yet.',

  businessProfilesTitle: 'Business Profiles',
  addNewProfile: 'Add New Profile',
  saveAsProfile: 'Save',
  businessProfilesDesc1: 'Switch instantly between saved business profiles.',
  businessProfilesDesc2: 'No saved profiles.',

  appUpdatesTitle: 'App Updates',
  appStorageDesc: 'App cache memory',
  appUpdatesDesc: 'Check if a newer version is available.',
  checkingUpdate: 'Checking...',
  checkForUpdates: 'Check for Updates',

  dataManagementTitle: 'Data Management',
  dataNoticeText: '<strong>Your data is stored locally on this device.</strong> It is never uploaded anywhere unless you manually sync to your personal Google Drive.',
  dataManagementDesc: 'Manage your backups and restorations.',
  exportBackup: 'Export Backup...',
  importBackup: 'Import Backup...',
  



  // Reports page
  reportsTitle: 'Reports',
  reportsSubtitle: 'Overview of your sales revenue and taxes collected',
  filterByLabel: 'Filter By',
  fiscalYearLabel: 'Fiscal Year',
  monthYearLabel: 'Month / Year',
  monthLabel: 'Month',
  yearLabel: 'Year',
  currencyLabel: 'Currency',
  revenueExTax: 'Revenue (ex. Tax)',
  salesSummaryTitle: 'Sales Summary',
  showingCurrencyInvoicesOnly: 'invoices only',
  totalRevenueLabel: 'Total Revenue',
  lessGstCollectedLabel: 'Less: Tax Collected',
  netRevenueLabel: 'Net Revenue',
  monthlySalesTitle: 'Monthly Sales Breakdown',
  revenueCol: 'Revenue',

  // Dashboard
  recentActivity: 'Recent Activity',
  totalItems: 'Total',
  seeAll: 'See All',
  newInvoice: 'New Invoice',
  editInvoice: 'Edit Invoice',
  item: 'Item',
  dashboard: 'Dashboard',
  companies: 'Companies',
  totalBills: 'Total Bills',
  greeting: 'Hello',
  primaryLanguage: 'Primary Language',
  secondaryLanguage: 'Secondary Language',
  bilingualBills: 'Bilingual Bills',
  enabled: 'Enabled',
  disabled: 'Disabled',
  languagesUsedForBilling: 'Languages used for billing and data entry',
  enableBilingualBills: 'Enable Bilingual Bills',
  showItemizedGstTable: 'Show GST splits in table',
  displayDetailedItemizedGst: 'Display detailed itemized GST breakdown columns on the invoice',
  overviewOfInvoices: 'Overview of your invoices',
  totalInvoiced: 'Total Invoiced',
  taxCollected: 'Tax Collected',
  overdueLabel: 'Overdue',
  
  // Dropdowns
  invoiceModeGoods: 'Goods',
  invoiceModeServices: 'Services',
  invoiceModeMixed: 'Mixed',
  noneLabel: 'None',
  selectLabelGeneric: 'Select',
  langTamil: 'தமிழ் (Tamil)',
  langEnglish: 'English',
  langHindi: 'हिन्दी (Hindi)',
  langTelugu: 'తెలుగు (Telugu)',
  langKannada: 'ಕನ್ನಡ (Kannada)',
  langMalayalam: 'മലയാളം (Malayalam)',
  langMarathi: 'मराठी (Marathi)',
  langGujarati: 'ગુજરાતી (Gujarati)',
  langBengali: 'বাংলা (Bengali)',
  paymentCash: 'Cash',
  paymentUPI: 'UPI',
  paymentBank: 'Bank Transfer',
  paymentCheque: 'Cheque',
  paymentCard: 'Card',
  paymentOther: 'Other',
  outstanding: 'Outstanding',
  invoicesCount: 'Invoices',
  searchClientOrInvoice: 'Search client or invoice...',
  allYears: 'All Years',
  allTypes: 'All Types',
  allStatus: 'All Status',
  noInvoicesYet: 'No invoices yet.',
  noInvoicesMatch: 'No matching invoices.',
  createInvoiceBtn: 'Create Invoice',
  dateCol: 'Date',
  invoiceNoCol: 'Invoice No.',
  typeCol: 'Type',
  clientCol: 'Client',
  amountCol: 'Amount',
  paidCol: 'Paid',
  statusCol: 'Status',
  actionsCol: 'Actions',

  // Statuses
  status_unpaid: 'Unpaid',
  status_partial: 'Partial',
  status_paid: 'Paid',
  status_overdue: 'Overdue',

  // New Invoice
  draftOnly: 'Draft',
  downloadPdf: 'Download PDF',
  whatsapp: 'WhatsApp',
  ewayBill: 'E-Way Bill',
  invoiceType: 'Invoice Type',
  customize: 'Customize',
  thisInvoiceIsFor: 'This invoice is for',
  goods: 'Goods',
  services: 'Services',
  mixed: 'Mixed',
  typeClientName: 'Type to search client name or add new',
  egMumbai: 'e.g. Mumbai',
  selectState: 'Select State',
  optionalLabel: 'Optional',
  pdfPreviewHeader: 'PDF Preview',
  termsAndConditionsLabel: 'Terms & Conditions',

  // Invoice Types
  invoiceTypes_tax_invoice: 'Tax Invoice',
  invoiceTypes_proforma: 'Proforma Invoice',
  invoiceTypes_bill_of_supply: 'Bill of Supply',
  invoiceTypes_composition: 'Composition Invoice',
  invoiceTypes_credit_note: 'Credit Note',
  invoiceTypes_delivery_challan: 'Delivery Challan',
  invoiceDesc_tax_invoice: 'Standard invoice for B2B/B2C sales with tax',
  invoiceDesc_proforma: 'Estimated invoice or quote before actual sale',
  invoiceDesc_bill_of_supply: 'For selling tax-exempt items without charging tax',
  invoiceDesc_composition: 'For businesses under Composition scheme (flat tax)',
  invoiceDesc_credit_note: 'For sales returns or reducing the invoice amount',
  invoiceDesc_delivery_challan: 'For sending items on approval, job work, or branch transfer',
  
  // Products - Bulk Actions
  duplicateProductsTitle: 'Duplicate Products?',
  duplicateProductsMessage: 'Are you sure you want to create copies of the selected product(s)?',
  saveDuplicate: 'Save (Duplicate)',
  productsDuplicatedSuccess: 'Products duplicated successfully',
  errorDuplicating: 'Error duplicating',
  deleteProductsTitle: 'Delete Products?',
  deleteProductsMessage: 'Delete selected product(s)? This cannot be undone.',
  savedSuccessfully: "Saved successfully",
  errorLoadingCustomers: "Error loading customers",

  vanakkamTitle: 'Vanakkam!',
  whoIsWorkingToday: "Who's working today?",

  deletedSuccessfully: 'Deleted successfully',
  errorDeleting: 'Error deleting'
,
  hc_100Safe: "100% safe",
  hc_orStartManually: "Or start manually:",
  hc_1Doubleclick: "1. Double-click",
  hc_onYourDesktop: "on your Desktop",
  hc_2OrSearch: "2. Or search",
  hc_inStartMenu: "in Start Menu",
  hc_startingThisPageWillOpen: "Starting... this page will open automatically.",
  hc_typeACommandOrPage: "Type a command or page name\u2026",
  hc_yourDataIsSafe: "Your data is safe.",
  hc_updatesOnlyRefreshTheApp: "Updates only refresh the app code and dependencies \u2014 your",
  hc_pdfArchiveAre: "PDF archive are",
  hc_neverTouched: "never touched",
  hc_githubReleases: "GitHub Releases",
  hc_recommended: "Recommended:",
  hc_exportBackup: "Export Backup\u2026",
  hc_skipThisVersion: "Skip this version",
  hc_viewOnGithub: "View on GitHub",
  hc_updateNow: "Update Now",
  hc_launches: "launches",
  hc_devSwitchBilingualLanguage: "DEV: Switch bilingual language",
  hc_devLanguageSwitcher: "DEV: Language Switcher",
  hc_primaryLanguage: "Primary Language",
  hc_secondaryLanguage: "Secondary Language",
  hc_bilingualMode: "Bilingual Mode",
  hc_uiLanguage: "UI Language",
  hc_enterCustomerName: "Enter Customer Name",
  hc_enterCountryName: "Enter country name",
  hc_active: "Active",
  hc_yourExistingBankDetailsAre: "Your existing bank details are still on this profile.",
  hc_clickBelowToImportThem: "Click below to import them as the first Payment Account, then add more.",
  hc_defaultAccount: "Default account",
  hc_inactive: "Inactive",
  hc_setAsDefault: "Set as default",
  hc_moveUp: "Move up",
  hc_moveDown: "Move down",
  hc_egAaaaa1234a: "e.g. AAAAA1234A",
  hc_egHdfcCurrent1234: "e.g. HDFC Current \u2014 1234",
  hc_bankName: "Bank Name",
  hc_egHdfcinbb: "e.g. HDFCINBB",
  hc_egYourbusinesshdfcbank: "e.g. yourbusiness@hdfcbank",
  hc_egUseForExportClients: "e.g. Use for export clients only",
  hc_setAsDefaultAccount: "\u2b50 Set as default account",
  hc_preview: "Preview:",
  hc_formatStyle: "Format Style",
  hc_brandPrefix: "Brand Prefix",
  hc_egAcmeBk: "e.g. ACME, BK",
  hc_separator: "Separator",
  hc_prefix: "Prefix",
  hc_egRcpR: "e.g. RCP, R",
  hc_googleOauthClientId: "Google OAuth Client ID",
  hc_openGoogleCloudConsole: "Open Google Cloud Console",
  hc_driveFolderName: "Drive Folder Name",
  hc_status: "Status",
  hc_yourDataWillNotBe: "Your data will not be affected. Click below to update:",
  hc_preferences: "Preferences",
  hc_uiLanguageDataLanguages: "UI language, Data languages",
  hc_accountsInvoiceFormatsTerms: "Accounts, Invoice formats, Terms",
  hc_advanced: "Advanced",

  hc_appVersionsCache: "App versions, Cache",
  hc_selectASetting: "Select a setting",
  hc_exportBackup1: "Export Backup",
  hc_alsoSaveACopyTo: "Also save a copy to my Google Drive",
  hc_downloadBackup: "Download Backup",
  hc_restoreFromBackup: "Restore from Backup",
  hc_overwriteMatchingRecordsById: "overwrite matching records by ID",
  hc_welcomeToElvanNiril: "Welcome to Elvan Niril",
  hc_businessDetails: "Business Details",
  hc_businessName: "Business Name",
  hc_egSharmaConsultantsPvtLtd: "e.g. Sharma Consultants Pvt. Ltd.",
  hc_eg42MgRoadSector: "e.g. 42, MG Road, Sector 15, Gurugram 122001",
  hc_neededForAutoCgstsgstVs: "Needed for auto CGST/SGST vs IGST",
  hc_phoneMobile: "Phone / Mobile",
  hc_egHdfcBank: "e.g. HDFC Bank",
  hc_accountNumber: "Account Number",
  hc_eg12345678901234: "e.g. 12345678901234",
  hc_ifscCode: "IFSC Code",
  hc_egHdfc0001234: "e.g. HDFC0001234",
  hc_upiId: "UPI ID",
  hc_egBusinessupi: "e.g. business@upi",
  hc_businessLogo: "Business Logo",
  hc_pngjpgMax500kb: "PNG/JPG, max 500KB",
  hc_digitalSignature: "Digital Signature",
  hc_youreAllSet: "You're All Set!",
  hc_openSidebar: "Open sidebar",
  hc_closeSidebar: "Close sidebar",
  emptyKey: "\u0baa\u0ba3 \u0bb0\u0b9a\u0bc0\u0ba4\u0bc1",
  hc_paymentReceipt: "PAYMENT RECEIPT",
  hc_egAcmeCorp: "e.g. Acme Corp",
  hc_addressInEnglish: "Address in English",
  hc_cityInEnglish: "City in English",
  hc_countryInEnglish: "Country in English",
  hc_taxDataExport: "Tax Data Export",
  hc_fullYear: "Full Year",
  hc_totalInvoices: "Total Invoices",
  hc_taxCollected: "Tax Collected",
  hc_netPayable: "Net Payable",
  hc_invoicesForThisPeriod: "Invoices for this Period",
  hc_noInvoicesFoundForThis: "No invoices found for this period.",
  hc_invoiceNo: "Invoice No",
  hc_client: "Client",
  hc_taxableValue: "Taxable Value",
  hc_taxAmount: "Tax Amount",
  hc_type: "Type",
  hc_b2bTotal: "B2B Total",
  hc_creditdebitNotesTable9b: "Credit/Debit Notes \u2014 Table 9B",
  hc_noteNo: "Note No",
  hc_noItemsFound: "No items found.",
  hc_noDocumentsIssued: "No documents issued.",
  hc_natureOfSupplies: "Nature of Supplies",
  hc_na: "N/A",
  hc_table32IntermaanilamSuppliesTo: "Table 3.2 \u2014 Inter-maanilam Supplies to Unregistered Persons",
  hc_placeOfSupply: "Place of Supply",
  hc_details: "Details",
  hc_netItcAvailable: "Net ITC Available",
  hc_table6TaxPaymentSummary: "Table 6 \u2014 Tax Payment Summary",
  hc_outputTaxLiability: "Output Tax Liability",
  hc_lessItcClaimed: "Less: ITC Claimed",
  hc_netTaxPayable: "Net Tax Payable",
  hc_netGstPayable: "Net GST Payable",
  hc_howToUse: "How to use:",
  hc_import2bJson: "Import 2B JSON",
  hc_purchaseBills: "Purchase Bills",
  hc_importYourGstr2bJsonTo: "Import your GSTR-2B JSON to reconcile against your purchase records.",
  hc_supplier: "Supplier",
  hc_invoiceNo1: "Invoice No.",
  hc_2bValue: "2B Value",
  hc_booksValue: "Books Value",
  hc_diff: "Diff",
  hc_noEntriesMatchThisFilter: "No entries match this filter.",
  hc_whatThisIs: "What this is:",
  hc_form26q: "Form 26Q",
  hc_form27eq: "Form 27EQ",
  hc_invoicesWithTds: "Invoices with TDS",
  hc_totalTdsReceivable: "Total TDS receivable",
  hc_quarter: "Quarter",
  hc_section: "Section",
  hc_customizeTds: "Customize \u2192 TDS",
  hc_invoicesWithTcs: "Invoices with TCS",
  hc_totalTcsCollected: "Total TCS collected",
  hc_customizeTcs: "Customize \u2192 TCS",
  hc_steps: "Steps:",
  hc_dueR1By11th3b: "| Due: R1 by 11th, 3B by 20th of next month | Late fee: \u20b950/day",
  hc_gstr1ProTips: "GSTR-1 Pro Tips",
  hc_fastestMethod: "Fastest method:",
  hc_exportGstr1JsonFromThe: "Export GSTR-1 JSON from the GSTR-1 tab above \u2192 Go to GST portal \u2192 GSTR-1 \u2192 Prepare Offline \u2192 Download Offline Tool \u2192 Import JSON \u2192 Upload. Saves 90% of time.",
  hc_gstr3bProTips: "GSTR-3B Pro Tips",
  hc_fromJuly2025: "From July 2025:",
  hc_table3AutopopulatesFromGstr1: "Table 3 auto-populates from GSTR-1 \u2014 just VERIFY, don't re-enter values.",
  hc_itcMatching: "ITC matching:",
  hc_alwaysCheckGstr2bStatementBefore: "Always check GSTR-2B statement BEFORE claiming ITC. Go to Returns \u2192 GSTR-2B \u2192 Download. Only claim ITC that appears in GSTR-2B.",
  hc_payment: "Payment:",
  hc_interestCalculation: "Interest calculation:",
  hc_reverseCharge: "Reverse charge:",
  hc_whenToFileNilReturn: "When to File NIL Return",
  hc_youHad: "You had",
  hc_zeroOutwardSupplies: "ZERO outward supplies",
  hc_youHave: "You have",
  hc_noInputTaxCredit: "NO input tax credit",
  hc_toClaim: "to claim",
  hc_noTaxLiability: "NO tax liability",
  hc_noInwardSupplies: "NO inward supplies",
  hc_liableToReverseCharge: "liable to reverse charge",
  hc_ifAnyOfTheAbove: "If ANY of the above has a value, you MUST file a regular return \u2014 not NIL",
  hc_nilGstr3bFileAfterNil: "NIL GSTR-3B \u2014 File After NIL GSTR-1",
  hc_nilReturnQuickSummary: "NIL Return Quick Summary",
  hc_nilGstr1AndNilGstr3b: "NIL GSTR-1 and NIL GSTR-3B are",
  hc_separateReturns: "separate returns",
  hc_fileBoth: "\u2014 file both",
  hc_nilFilingTakes23Minutes: "NIL filing takes 2-3 minutes per return \u2014 just login, verify zeros, submit, file",
  hc_youCanFileNilReturns: "You can file NIL returns via SMS: Send",
  hc_nilSpaceGstinSpaceReturn: "NIL space GSTIN space Return Period",
  hc_to14409VerifyWithOtp: "to 14409. Verify with OTP.",
  hc_qrmpUsersFilingQuarterlyNil: "QRMP users filing quarterly: NIL return covers the entire quarter",
  hc_keyGstRulesToRemember: "Key GST Rules to Remember",
  hc_itcForAnyInvoiceMust: "ITC for any invoice must be claimed by the due date of September return of the following FY, or the date of filing annual return \u2014 whichever is earlier.",
  hc_section34: "Section 34:",
  hc_creditNotesMustBeIssued: "Credit notes must be issued before September 30 following the end of FY of the original invoice or annual return filing \u2014 whichever is earlier.",
  hc_section31: "Section 31:",
  hc_taxInvoiceMustBeIssued: "Tax invoice must be issued at or before the time of supply. For services, within 30 days of supply.",
  hc_section49: "Section 49:",
  hc_itcCanOnlyBeClaimed: "ITC can only be claimed for invoices that appear in GSTR-2B. No provisional ITC beyond GSTR-2B.",
  hc_section50: "Section 50:",
  hc_section7374: "Section 73/74:",
  hc_ewayBill: "E-way Bill:",
  hc_cannotGenerateEwayBillsIf: "Cannot generate e-way bills if GSTR-3B not filed for 2+ consecutive months.",
  hc_bulletList: "Bullet list",
  hc_numberedList: "Numbered list",
  hc_heading: "Heading",
  hc_paragraph: "Paragraph",
  hc_insertLink: "Insert link",
  hc_clearFormatting: "Clear formatting",
  hc_allChangesSaved: "All changes saved",
  hc_addAClientNameAnd: "Add a client name and at least one item to start saving",
  hc_sacCode: "SAC code",
  hc_invoiceTitle: "Invoice Title",
  hc_currency: "Currency",
  hc_paymentAccountOnThisInvoice: "Payment account on this invoice",
  hc_pdfStyle: "PDF Style",
  hc_accentColor: "Accent Color",
  hc_hideAll: "Hide all",
  hc_savedCustomer: "Saved Customer",
  hc_tempCustomer: "Temp Customer",
  hc_savedClientDetails: "Saved Client Details",
  hc_maanilamRegion: "maanilam / Region",
  hc_originalInvoiceReference: "Original Invoice Reference",
  hc_egInv2025260001: "e.g. INV/2025-26/0001",
  hc_savedItem: "Saved Item",
  hc_tempItem: "Temp Item",
  hc_searchSavedItems: "Search saved items...",
  hc_savedItemDetails: "Saved Item Details",
  hc_hsnsac: "HSN/SAC:",
  hc_unit: "Unit:",
  hc_tax: "Tax:",
  hc_cess: "Cess:",
  hc_addCustom: "\uff0b Add custom\u2026",
  hc_remove: "Remove",
  hc_saveChangesBeforeClosing: "Save changes before closing?",
  hc_forEstimationPurposesOnly: "For estimation purposes only",
  hc_against: "Against:",
  hc_thisIsNotATax: "This is not a tax invoice. For estimation purposes only.",
  hc_againstInvoice: "Against Invoice:",
  hc_disc: "Disc.",
  hc_subtotal: "Subtotal",
  hc_gstCess: "GST Cess",
  hc_roundoff: "Round-off",
  hc_netReceivable: "Net Receivable",
  hc_reverseChargeApplicable: "Reverse Charge applicable.",
  hc_exchangeRate: "EXCHANGE RATE"
,

  // Auto-added missing keys
  totalDueLabel: "Total Due",
  descriptionCol: "Description",
  hsnSacCol: "HSN/SAC",
  rateCol: "Rate",
  addItemBtn: "Add Item",
  termsHeading: "Terms Heading",
  insertPreset: "Insert Preset",
  pickBusinessType: "Pick Business Type",
  indiaSpecificStarter: "India Specific Starter",
  loadSavedTemplate: "Load Saved Template",
  termsAppearsOnInvoice: "Terms Appears On Invoice",
  privateNote: "Private Note",
  privateNoteEg: "Private Note Eg",
  additionalPages: "Additional Pages",
  addSectionBtn: "Add Section",
  addExtraSectionsDesc: "Add Extra Sections Desc",
  noExtraSections: "No Extra Sections",
  clientsTitle: "Clients",
  clientsSubtitle: "Manage clients and view outstandings",
  importCSV: "Import CSV",
  newInvoiceBtn: "New Invoice",
  searchClients: "Search Clients",
  noClientsFound: "No Clients Found",
  addFirstClient: "Add First Client",
  invoiceCountSingular: "Invoice Count Singular",
  totalLabel: "Total",
  paidLabel: "Paid",
  outstandingLabel: "Outstanding",
  hideLabel: "Hide",
  viewLabel: "View",
  noInvoicesForClient: "No Invoices For Client",
  removeSavedClientConfirm: "Remove Saved Client Confirm",
  clientRemoved: "Client Removed",
  deleteInvoiceConfirm: "Delete Invoice Confirm",
  invoiceDeleted: "Invoice Deleted",
  failedToDelete: "Failed To Delete",
  editClientBtn: "Edit Client",
  deleteClientBtn: "Delete Client",
  saveAsClientBtn: "Save",
  selectLabel: "Select",
  sezUnitTitle: "Sez Unit",
  addProductBtn: "Add Product",
  searchProducts: "Search Products",
  productNamePlaceholder: "Product Name Placeholder",
  hsnCodePlaceholder: "Hsn Code Placeholder",
  unitLabel: "Unit",
  stockQuantityLabel: "Stock Quantity",
  descriptionLabelOptional: "Description Label Optional",
  descriptionPlaceholder: "Description Placeholder",
  productsAndServices: "Products And Services",
  noProductsYet: "No Products Yet",
  noProductsMatch: "No Products Match",
  outOfStock: "Out Of Stock",
  deleteProductConfirmMsg: "Delete Product Confirm",
  productDeletedToast: "Product Deleted",
  failedToLoadProductsToast: "Failed To Load Products",
  emptyCsvWarningToast: "Empty Csv Warning",
  failedToParseCsvToast: "Failed To Parse Csv",
  nameCol: "Name",
  hsnCol: "Hsn",
  stockCol: "Stock",
  receiptsSubtitle: "Manage payment receipts",
  newReceiptBtn: "New Receipt",
  quickSelectUnpaid: "Quick Select Unpaid",
  receiptNoLabel: "Receipt No",
  dateLabel: "Date",
  receivedFromLabel: "Received From",
  amountLabelStar: "Amount Label",
  paymentModeLabel: "Payment Mode",
  referenceNoLabel: "Reference No",
  againstInvoiceLabel: "Against Invoice",
  againstInvoicePlaceholder: "Against Invoice Placeholder",
  noteOptionalLabel: "Note Optional",
  saveReceiptBtn: "Save",
  searchReceipts: "Search Receipts",
  paymentReceiptsTableTitle: "Payment Receipts Table",
  noReceiptsYet: "No Receipts Yet",
  noReceiptsMatch: "No Receipts Match",
  createReceiptBtn: "Create Receipt",
  againstInvoiceCol: "Against Invoice",
  modeCol: "Mode",
  clientNameRequiredToast: "Client Name Required",
  enterValidAmountToast: "Enter Valid Amount",
  receiptSavedToast: "Receipt Saved",
  deleteReceiptConfirmMsg: "Are you sure you want to delete this receipt?",
  deletedToast: "Deleted",
  expensesSubtitle: "Track business expenses",
  exportCsvBtn: "Export CSV",
  addExpenseBtn: "Add Expense",
  totalExpensesCard: "Total Expenses",
  gstPaidCard: "Gst Paid",
  entriesCard: "Entries",
  searchExpenses: "Search Expenses",
  allCategoriesFilter: "All Categories Filter",
  expenseRecordsTable: "Expense Records Table",
  noExpensesYet: "No Expenses Yet",
  noExpensesMatch: "No Expenses Match",
  editExpenseTitle: "Edit Expense",
  addExpenseTitle: "Add Expense",
  dateLabelStar: "Date Label",
  categoryLabel: "Category",
  descriptionLabelStar: "Description Label",
  descriptionPlaceholderExp: "Description Placeholder Exp",
  amountGstLabelStar: "Amount Gst Label",
  gstPercentItcLabel: "Gst Percent Itc",
  vendorNameLabel: "Vendor Name",
  vendorNameOptional: "Vendor Name Optional",
  vendorGstinLabel: "Vendor Gstin",
  vendorGstinHint: "Vendor Gstin Hint",
  invoiceBillNoLabel: "Invoice Bill No",
  descriptionRequiredToast: "Description Required",
  enterValidAmountToastExp: "Enter Valid Amount Toast Exp",
  expenseUpdatedToast: "Expense Updated",
  expenseAddedToast: "Expense Added",
  failedToSaveExpenseToast: "Failed To Save Expense",
  deleteExpenseConfirmMsg: "Delete Expense Confirm",
  expenseDeletedToast: "Expense Deleted",
  noExpensesToExportToast: "No Expenses To Export",
  expensesCsvDownloadedToast: "Expenses Csv Downloaded",
  gstCol: "Gst",
  vendorCol: "Vendor",
  purchasesSubtitle: "Track supplier bills for ITC",
  addPurchaseBtn: "Add Purchase",
  totalPurchasesCard: "Total Purchases",
  gstItcEligibleCard: "Gst Itc Eligible",
  searchSupplierInvoice: "Search Supplier Invoice",
  purchaseRecordsTable: "Purchase Records Table",
  noPurchaseBillsYet: "No Purchase Bills Yet",
  noPurchasesMatch: "No Purchases Match",
  editPurchaseBillTitle: "Edit Purchase Bill",
  addPurchaseBillTitle: "Add Purchase Bill",
  paymentStatusLabel: "Payment Status",
  supplierNameLabel: "Supplier Name",
  supplierNamePlaceholder: "Supplier Name Placeholder",
  supplierGstinLabel: "Supplier Gstin",
  supplierGstinPlaceholder: "Supplier Gstin Placeholder",
  invoiceNumberLabel: "Invoice Number",
  invoiceNumberPlaceholder: "Invoice Number Placeholder",
  interstatePurchaseLabel: "Interstate Purchase",
  interstatePurchaseDesc: "Interstate Purchase Desc",
  interstatePurchaseTip: "Interstate Purchase Tip",
  itemsTitle: "Items",
  qtyCol: "Qty",
  taxPercentCol: "Tax Percent",
  taxableLabelText: "Taxable Label Text",
  taxLabelText: "Tax Label Text",
  totalLabelText: "Total Label Text",
  supplierNameRequiredToast: "Supplier Name Required",
  invoiceNumberRequiredToast: "Invoice Number Required",
  purchaseUpdatedToast: "Purchase Updated",
  purchaseAddedToast: "Purchase Added",
  failedToSavePurchaseToast: "Failed To Save Purchase",
  failedToLoadPurchasesToast: "Failed To Load Purchases",
  deletePurchaseConfirmMsg: "Delete Purchase Confirm",
  purchaseDeletedToast: "Purchase Deleted",
  noPurchasesToExportToast: "No Purchases To Export",
  purchasesCsvDownloadedToast: "Purchases Csv Downloaded",
  supplierCol: "Supplier",
  gstinCol: "Gstin",
  taxableCol: "Taxable",
  recurringInvoicesSubtitle: "Automate invoices for regular clients",
  newTemplateBtn: "New Template",
  dueForGeneration: "Due For Generation",
  editTemplateTitle: "Edit Template",
  newRecurringInvoiceTitle: "New Recurring Invoice",
  quickSelectClient: "Quick Select Client",
  frequencyLabel: "Frequency",
  nextDueDateLabel: "Next Due Date",
  invoiceTypeLabel: "Invoice Type",
  lineItemsTitle: "Line Items",
  recurringTemplatesTable: "Recurring Templates Table",
  noRecurringYet: "No Recurring Yet",
  createTemplateBtn: "Create Template",
  frequencyCol: "Frequency",
  nextDueCol: "Next Due",
  addAtLeastOneItemToast: "Add At Least One Item",
  templateUpdatedToast: "Template Updated",
  recurringCreatedToast: "Recurring Created",
  deleteTemplateConfirmMsg: "Delete Template Confirm",
  pausedToast: "Paused",
  activatedToast: "Activated",
  failedToGenerateToast: "Failed To Generate",
  invoiceGeneratedFor: "Invoice Generated For",
  freqWeekly: "Freq Weekly",
  freqMonthly: "Freq Monthly",
  freqQuarterly: "Freq Quarterly",
  freqYearly: "Freq Yearly",
  statusActive: "Status Active",
  statusPaused: "Status Paused",
  generateNowTooltip: "Generate Now Tooltip",
  pauseTooltip: "Pause Tooltip",
  activateTooltip: "Activate Tooltip",
  profitAndLossTab: "Profit And Loss",
  outstandingAndAgingTab: "Outstanding And Aging",
  expensesExGst: "Expenses Ex Gst",
  netProfitLabel: "Net Profit",
  netLossLabel: "Net Loss",
  marginLabel: "Margin",
  plStatementTitle: "Pl Statement",
  totalExpensesLabel: "Total Expenses",
  lessGstOnExpensesLabel: "Less Gst On Expenses",
  netExpensesLabel: "Net Expenses",
  monthlyBreakdownTitle: "Monthly Breakdown",
  expensesCol: "Expenses",
  profitLossCol: "Profit Loss",
  totalOutstandingLabel: "Total Outstanding",
  current0to30d: "Current 0 to 30 Days",
  days31to60: "Days 31 to 60",
  days61to90: "Days 61 to 90",
  days90plus: "Days 90 plus",
  filterByClientName: "Filter By Client Name",
  outstandingReceivablesTitle: "Outstanding Receivables",
  noOutstandingFound: "No Outstanding Found",
  dueDateCol: "Due Date",
  outstandingCol: "Outstanding",
  daysOverdueCol: "Days Overdue",
  currentStatus: "Current Status",
  january: "January",
  february: "February",
  march: "March",
  april: "April",
  may: "May",
  june: "June",
  july: "July",
  august: "August",
  september: "September",
  october: "October",
  november: "November",
  december: "December",
  gstReturnsTitle: "GST Returns",
  gstReturnsSubtitle: "Manage your GST Returns and filing status",
  monthlyTab: "Monthly",
  quarterlyTab: "Quarterly",
  r1Pending: "R1 Pending",
  b3Pending: "3B Pending",
  gstPortalBtn: "Gst Portal",
  gstinNotSet: "GSTIN not set. Please add it in Settings.",
  invoicesCountLabel: "Invoices Count",
  taxableLabel: "Taxable",
  taxLabel: "Tax",
  netPayableLabel: "Net Payable",
  gstr1Tab: "GSTR-1",
  gstr3bTab: "GSTR-3B",
  gstr2bReconTab: "GSTR-2B Recon",
  tdsTcsTab: "Tds Tcs",
  filingGuideTab: "Filing Guide",
  jsonExportBtn: "Json Export",
  docsBtn: "Docs",
  markFiledBtn: "Mark Filed",
  b2bSalesTable: "B2B Sales",
  b2cSalesTable: "B2C Sales",
  hsnSummaryTable: "HSN Summary",
  docSummaryTable: "Document Summary",
  gstr1SummaryTotals: "GSTR-1 Summary Totals",
  noB2bInvoices: "No B2B Invoices",
  noB2cInvoices: "No B2C Invoices",
  cgstCol: "CGST",
  sgstCol: "SGST",
  igstCol: "IGST",
  totalCol: "Total",
  b2cTotal: "B2C Total",
  totalTaxCol: "Total Tax",
  docTypeCol: "Doc Type",
  fromCol: "From",
  toCol: "To",
  totalIssuedCol: "Total Issued",
  categoryCol: "Category",
  grandTotal: "Grand Total",
  b2bSalesCategory: "B2B Sales Category",
  b2cSalesCategory: "B2C Sales Category",
  invoiceWord: "Invoice",
  invoicesWord: "Invoices",
  codeWord: "Code",
  codesWord: "Codes",
  notificationsTitle: "Notifications",
  allClearNotif: "All Clear",
  recurringAutoFireNotif: "Recurring Auto Fire",
  checkDashboardForNewBills: "Check Dashboard For New Bills",
  overdueInvoicesNotif: "Overdue Invoices",
  moreWord: "More",
  dueIn3DaysNotif: "Due In 3 Days",
  gstFilingsDueNotif: "Gst Filings Due",
  todayWord: "Today",
  lowStockNotif: "Low Stock",
  leftWord: "Left",
  hc_discardChanges: "Discard Changes",
  hc_discardWarning: "Are you sure you want to discard your unsaved changes?",
  hc_cancel: "Cancel",
  hc_discard: "Discard",
  receiptDetails: "Receipt Details",
  invoiceData: "Invoice Data",
  receiptData: "Receipt Data",
  invoicesSelected: "invoice(s) selected",
  paymentDetails: "Payment Details",
  productDetails: "Product Details",
  pricingAndTax: "Pricing & Tax",
  clientDetails: "Client Details",
  addressDetails: "Address Details",
  contactAndTaxDetails: "Contact & Tax Details",
  hc_addNewProduct: "Add New Product",
  hc_addNewClient: "Add New Customer",
  deleteInvoiceConfirmMsg: "Are you sure you want to delete this invoice?",
  notesAndTerms: "Notes / Terms",
  customer: "Customer",
  company: "Company",
  quantity: "Quantity",
  addOtherCharges: "Add Other Charges",
  chargeName: "Charge Name",
  otherCharges: "Other Charges",
  setharam: "Setharam",
  ahimsaSilk: "Ahimsa Silk",
  courier: "Courier",
  totalWeight: "Total Weight",
  grams: "Grams",
  searchBillsPlaceholder: "Search anything...",
  saveBtn: 'Save',
  bankNameTamil: 'Bank Name (Tamil)',
  bankNameEnglish: 'Bank Name (English)',
  branchNameTamil: 'Branch Name (Tamil)',
  branchNameEnglish: 'Branch Name (English)',
  manage: 'Manage',
  addNew: 'Add New',
  shortBusinessNameLabel: 'Short Business Name (for Bill No)',
  shortBusinessNameHelper: 'Used as the default prefix for your invoice numbers.',
  authorizedSignatoryName: 'Authorized Signatory Name',
  profileSaved: 'Profile saved!',
  unsavedChangesWarning: 'You have unsaved changes. Continue without saving?',
  unsavedChanges: 'Unsaved changes',
  discardBtn: 'Discard',
  savingStatus: 'Saving...',
  createNewProfile: 'Create New Profile',
  businessNameAsterisk: 'Business Name *',
  addressLabel: 'Address',
  manageBusinessProfiles: 'Manage Business Profiles',
  noSavedProfiles: 'No saved profiles yet',
  confirmDeleteTitle: 'Confirm Delete',
  english1: 'English',
  all: 'All',
  measureType: 'Measure Type',
  invoiceCount: 'Invoice Count',
  selectYourOperatingMode: 'Select your operating mode',
  languageSettingsSaved: 'Language settings saved!',
  usedAsTheDefaultPrefixForYourI: 'Used as the default prefix for your invoice numbers (e.g. SJS/2026-27/0001).',
  addAlternateMobile: 'Add Alternate Mobile',
  changeTheLanguageOfTheApplicat: 'Change the language of the application.',
  appUserName: 'App User Name',
  thisNameWillAppearOnTheAppHome: 'This name will appear on the app home screen profile pill.',
  userName: 'User Name',
  allowDataEntryInTwoLanguages: 'Allow data entry in two languages',
  bankDetailsShownOnYourInvoices: 'Bank details shown on your invoices.',
  accountNumber: 'Account Number',
  uPIIDOptional: 'UPI ID (optional)',
  totals: 'Totals',
  subtotal: 'Subtotal',
  totalDiscountAmt: 'Total Discount Amount',
  roundOff: 'Round Off',
  noInvoicesFound: 'No Invoices Found',
  featureNotSupported: 'Feature Not Supported',

  addressTamil: 'Address (Tamil)',
  addressEnglish: 'Address (English)',
  organizationLogo: 'Organization Logo',
  upcomingFeature: 'Upcoming Feature',
  cityTamil: 'City (Tamil)',
  cityEnglish: 'City (English)',
  districtTamil: 'District (Tamil)',
  districtEnglish: 'District (English)',
  cityLabel: 'City',
  districtLabel: 'District',
  pincode: 'Pincode',
  branchTamil: 'Branch (Tamil)',
  branchEnglish: 'Branch (English)',
  appearanceDescription: 'Configure bill theme color and print languages.',
  billTheme: 'Bill Theme Color',
  defaultPrintLanguage: 'Bill & Receipt Language',
  receiptLanguage: 'Receipt Language',
  accountSecurityTitle: 'Account Security',
  accountSecurityDesc: 'Lock app access.',
  signOutBtn: 'Sign Out',
  eraseAppDataTitle: 'Erase App Data',
  eraseAppDataDesc: 'Permanently wipe all records.',
  eraseDataBtn: 'Erase Data',
  systemAndSecurity: 'System & Security',
  systemSecurityDesc: 'Clear cache, Account security, Updates',
  clearCacheTitle: 'Clear Cache',
  clearCacheDesc: 'Fix issues by clearing cache.',
  clearCacheBtn: 'Clear Cache',

  clearCacheConfirmDesc: 'This will reload the app. You may need to sign in again.',
  signOutConfirmTitle: 'Sign Out?',
  signOutConfirmDesc: 'Are you sure you want to sign out? You will need your password to access your data again.',
  eraseConfirmDesc: 'Permanently deletes all cloud data. This cannot be undone.',
  confirmEmailLabel: 'Confirm Email',
  incorrectEmail: 'Email does not match.',
  confirmPassword: 'Confirm Password',
  password: 'Password',
  erasing: 'Erasing...',
  enterPassword: 'Please enter your password',
  dataErasedSuccess: 'App data erased.',
  incorrectPassword: 'Incorrect password.',
  tooManyRequests: 'Too many attempts. Try later.',
  errorOccurred: 'Failed to erase data.',

  welcomeTitle: 'Welcome to Niril',
  welcomeSubtitle: 'Your Billing & GST, Sorted.',
  welcomeAgreeText: 'Tap "Get Started" to continue with Niril.',
  agreeAndContinueBtn: 'Get Started',
  selectLanguageTitle: 'Select Language',
  selectLanguageSubtitle: 'Choose your preferred language',
  editPrefix: 'Edit '
};
